
var D2L_MathML={m_browserInfo:null,m_characterEntities:null,m_mathDisplayType:null};D2L_MathML.MathDisplayType={WebEQ:0,MathML:1,MathPlayer:2};D2L_MathML.BrowserType={Unknown:0,Firefox:1,IE:2,Safari:3,Chrome:4,Opera:5};D2L_MathML.IEBrowserMode={None:0,IE7:1,IE8:2,IE8Compatibility:3};D2L_MathML.AssignHtml=function(b,c){b.innerHTML=D2L_MathML.ConvertMathML(c);D2L_MathML.RenderMathML()};
D2L_MathML.MathSizeInfo=function(b){this.m_height=this.m_width=0;this.m_isAuto=true;if(b!==undefined){b=b.match(/<annotation[^>]*>(.|\n|\r)*?<\/annotation>/i);if(b!=null&&b.length>0){b=b[0].replace("&quot;",'"').match(/"size":{"width":"(\d*)","height":"(\d*)","auto":(\w*)}/i);if(b!=null){this.m_width=parseInt(b[1]);this.m_height=parseInt(b[2]);this.m_isAuto=b[3]=="true"}}}this.GetHeight=function(){return this.m_height};this.GetWidth=function(){return this.m_width};this.IsAuto=function(){return this.m_isAuto};
this.SetHeight=function(c){this.m_height=c};this.SetIsAuto=function(c){this.m_isAuto=c};this.SetWidth=function(c){this.m_width=c};this.ToString=function(){return'"size":{"width":"'+this.m_width+'","height":"'+this.m_height+'","auto":'+this.m_isAuto+"}"}};
D2L_MathML.BrowserInfo=function(){this.m_version=this.m_type=null;this.m_hasMathPlayer=false;this.m_ieBrowserMode=D2L_MathML.IEBrowserMode.None;var b=navigator.userAgent;if(/Firefox[\/\s](\d+\.\d+)/.test(b)){this.m_type=D2L_MathML.BrowserType.Firefox;this.m_version=new Number(RegExp.$1)}else if(/Opera[\/\s](\d+\.\d+)/.test(b)){this.m_type=D2L_MathML.BrowserType.Opera;this.m_version=new Number(RegExp.$1)}else if(/MSIE (\d+\.\d+);/.test(b)){this.m_type=D2L_MathML.BrowserType.IE;this.m_version=new Number(RegExp.$1);
this.m_hasMathPlayer=/MathPlayer/.test(b);if(this.m_version==7){if(document.documentMode){this.m_version=8;this.m_ieBrowserMode=/trident\/\d/i.test(b)?D2L_MathML.IEBrowserMode.IE8Compatibility:D2L_MathML.IEBrowserMode.IE7}}else if(this.m_version==8)this.m_ieBrowserMode=D2L_MathML.IEBrowserMode.IE8}else if(/Chrome[\/\s](\d+\.\d+)/.test(b)){this.m_type=D2L_MathML.BrowserType.Chrome;this.m_version=new Number(RegExp.$1)}else if(/Safari[\/\s](\d+\.\d+)/.test(b)){this.m_type=D2L_MathML.BrowserType.Safari;
if(/Version[\/\s](\d+\.\d+)/.test(b))this.m_version=new Number(RegExp.$1)}else{this.m_type=D2L_MathML.BrowserType.Other;this.m_version=null}this.HasMathPlayer=function(){return this.m_hasMathPlayer};this.GetIEBrowserMode=function(){return this.m_ieBrowserMode};this.GetType=function(){return this.m_type};this.GetVersion=function(){return this.m_version};this.ToString=function(){return"D2L MathML Browser Info: \n\n  Browser: "+this.m_type+"\n  Version: "+this.m_version+"\n  MathPlayer: "+this.m_hasMathPlayer}};
D2L_MathML.ConvertMathDisplayTypeToEnum=function(b){return b=="webeq"?D2L_MathML.MathDisplayType.WebEQ:D2L_MathML.MathDisplayType.MathML};
D2L_MathML.ConvertMathML=function(b,c){var e=b;b=b.match(/(?!")<math[^>]*(.|\n|\r)*?<\/math>(?!")/gi);if(b!=null&&b.length>0){if(c==null)c=D2L_MathML.GetMathDisplayType();var f=null;switch(c){case D2L_MathML.MathDisplayType.MathML:break;case D2L_MathML.MathDisplayType.MathPlayer:break;case D2L_MathML.MathDisplayType.WebEQ:f=D2L_MathML.ConvertToWebEQ;break;default:}if(f!=null)for(c=0;c<b.length;c++)e=e.replace(b[c],f(b[c]))}return e};
D2L_MathML.ConvertToWebEQ=function(b){var c="",e=b.match(/<math[^>]*(.|\n|\r)*?>/gi);if(e!=null&&e.length>0){c=e[0].replace(/\'/g,'"');e=c.match(/title\s*=\s*(\"[^\"]*\"|[^\s]*)\s*/i);c=e!=null&&e.length>1?e[1].replace(/\"/g,""):""}e=b.match(/<semantics[^>]*(.|\n|\r)*?<\/semantics>/gi);if(e!=null&&e.length>0)b=e[0];e=D2L_MathML.GetMathSizeInfo(b);b=b.replace(/<annotation[^>]*>(.|\n|\r)*?<\/annotation>/gi,"");b="<math>"+b+"</math>";b=D2L_MathML.EncodeMathML(b);c='<applet alt="'+c+'" style="height:'+
e.GetHeight()+"px; width:"+e.GetWidth()+'px;" archive="/math/classes/WebEQApplet.jar" codebase="/math/classes" code="webeq3.ViewerControl" align="middle" >';c+='<param name="useslibrary" value="WebEQApplet"></param>';c+='<param name="useslibrarycodebase" value="/math/classes/WebEQApplet.cab"></param>';c+='<param name="eq" value="'+b+'" ></param>';c+='<param name="valign" value="middle"></param>';c+='<param name="foreground" value="black"></param>';c+='<param name="background" value="white"></param>';
c+='<param name="selection" value="true"></param>';c+='<param name="parser" value="mathml"></param></applet>';return c};
D2L_MathML.CreateAnnotatedMathML=function(b,c,e,f,g,h,k){if(c===undefined)c="";if(f===undefined)f=0;if(e===undefined)e=0;if(g===undefined)g=true;k=k.replace(/<math[^>]*>/gi,"");k=k.replace(/<\/math>/gi,"");c='<math title="'+c+'" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mstyle>';c+=k;c+='</mstyle><annotation encoding="'+b+'">';c+='{"version":"1.0","size":{"width":"'+e+'","height":"'+f+'","auto":'+g+'},"math":"'+D2L.Util.Html.Encode(h)+'"}';c+="</annotation></semantics></math>";return c};
D2L_MathML.EncodeMathML=function(b){if(b!=undefined&&b.encodeMathML!==undefined)return b.encodeMathML();return b};D2L_MathML.CloseTags=function(b){if(b!=null)b=b.replace(/<(mspace|mprescripts|mglyph|malignmark|maligngroup|none)([^>]*)\/>/gi,"<$1$2></$1>");return b};D2L_MathML.GetCharacterEntities=function(){if(D2L_MathML.m_characterEntities==null)D2L_MathML.m_characterEntities=new D2L_MathML.CharacterEntities;return D2L_MathML.m_characterEntities};
D2L_MathML.GetBrowserInfo=function(){if(D2L_MathML.m_browserInfo==null)D2L_MathML.m_browserInfo=new D2L_MathML.BrowserInfo;return D2L_MathML.m_browserInfo};D2L_MathML.GetMathDisplayType=function(){if(D2L_MathML.m_mathDisplayType==null){D2L_MathML.m_mathDisplayType=D2L_MathML.MathDisplayType.WebEQ;var b=window.Global;if(b!==undefined)D2L_MathML.m_mathDisplayType=D2L_MathML.ConvertMathDisplayTypeToEnum(b.Preferences.MathDisplayType)}return D2L_MathML.m_mathDisplayType};D2L_MathML.GetMathSizeInfo=function(b){return new D2L_MathML.MathSizeInfo(b)};
D2L_MathML.RenderMathML=function(b,c,e){if(c===undefined)c=document;if(e===undefined)e=D2L_MathML.GetMathDisplayType();b=c.getElementsByTagName("math");if(b.length!==0){c=null;switch(e){case D2L_MathML.MathDisplayType.MathML:c=D2L_MathML.RenderAsMathML;break;case D2L_MathML.MathDisplayType.MathPlayer:c=D2L_MathML.RenderAsMathPlayer;break;case D2L_MathML.MathDisplayType.WebEQ:c=D2L_MathML.RenderAsWebEQ;break;default:}e=[];for(var f=0;f<b.length;f++)e.push(b[f]);for(f=0;f<e.length;f++)c(e[f])}};
D2L_MathML.RenderAsMathML=function(b){var c=D2L_MathML.GetBrowserInfo(),e=b.getAttribute(" title"),f=D2L_MathML.GetCharacterEntities(),g=function(k){if(k.nodeType==1){var j=null;j=c.GetType()==D2L_MathML.BrowserType.Firefox?document.createElementNS("http://www.w3.org/1998/Math/MathML",k.nodeName.toLowerCase()):document.createElement(k.nodeName.toLowerCase());for(var l=0;l<k.attributes.length;l++)j.setAttribute(k.attributes[l].nodeName,k.attributes[l].nodeValue);for(l=0;l<k.childNodes.length;l++){var o=
true;if(k.childNodes[l].nodeName.toLowerCase()=="annotation"&&c.GetType()!=D2L_MathML.BrowserType.Firefox)o=false;if(o){o=k.childNodes[l].nodeValue;o=f.Translate(o);k.childNodes[l].nodeValue=o;if(o==null||o.slice(0,1)!=" "&&o.slice(0,1)!="\n")j.appendChild(g(k.childNodes[l]))}}return j}else return k},h=g(b);e!=null&&h.setAttribute("title",e);b.parentNode.replaceChild(h,b)};
D2L_MathML.RenderAsMathPlayer=function(b){var c=b.outerHTML.match(/<math[^>]*>(.|\n|\r)*?<\/math>/gi)[0];c=c.replace(/<math[^>]*>/gi,"");c=c.replace(/<\/math>/gi,"");c=c.replace(/<(?!\/)/g,"<m:");c=c.replace(/<\/(?=\w)/g,"</m:");var e=document.getElementById("mathMLContainer");if(e==null){e=document.createElement("div");e.id="mathMLContainer";e.style.display="none";document.appendChild(e)}e.innerHTML="<m:math></m:math>";e=e.firstChild;e.innerHTML=c;e.update();b.parentNode.replaceChild(e,b)};
D2L_MathML.RenderAsWebEQ=function(b){var c=D2L_MathML.ConvertToWebEQ(b.parentNode.innerHTML),e=document.createElement("span");e.innerHTML=c;c=new D2L_MathML.GetBrowserInfo;if(c.GetType()==D2L_MathML.BrowserType.IE&&c.GetVersion()<8||c.GetType()==D2L_MathML.BrowserType.IE&&c.GetVersion()<8&&c.GetIEBrowserMode()==D2L_MathML.IEBrowserMode.IE7){c=null;for(var f=[],g=0;g<b.parentNode.childNodes.length;g++){c=b.parentNode.childNodes[g];if(c.tagName!="MATH")f.push(c);else if(c.tagName=="/MATH")break}for(g=
0;g<f.length;g++)b.parentNode.removeChild(f[g])}b.parentNode.replaceChild(e.childNodes[0],b)};D2L_MathML.SetMathDisplayType=function(b){D2L_MathML.m_mathDisplayType=b};
D2L_MathML.UpdateMathSizeInfo=function(b,c,e){if(typeof c=="string"&&c!=null&&c.substr(c.length-2,2)=="px")c=c.substr(0,c.length-2);if(typeof e=="string"&&e!=null&&e.substr(e.length-2,2)=="px")e=e.substr(0,e.length-2);var f=D2L_MathML.GetMathSizeInfo(b);if(f.GetHeight()!=e||f.GetWidth()!=c){var g=new D2L_MathML.MathSizeInfo;g.SetHeight(e);g.SetWidth(c);g.SetIsAuto(false);b=b.replace(f.ToString(),g.ToString())}return b};
String.prototype.encodeMathML=function(){var b=this.toString();if(b.indexOf("&")!=-1||b.indexOf("<")!=-1||b.indexOf(">")!=-1||b.indexOf('"')!=-1){b=b.replace(/\&/g,"&amp;");b=b.replace(/\</g,"&lt;");b=b.replace(/\>/g,"&gt;");b=b.replace(/\"/g,"&quot;");b=b.replace(/&amp;amp;[\S]*?;/g,function(c){return c.replace("&amp;amp;","&")})}return b};
D2L_MathML.CharacterEntities=function(){var b=this.m_entities={},c=D2L_MathML.CharacterEntity;this.Translate=function(e){var f=this,g=function(h){var k=f.m_entities[h];return k!==undefined?k.GetCharacter():h};return e!=null?e.replace(/&[\S]*?;/g,g):null};this.GetEntities=function(){return this.m_entities};b["&aacute;"]=new c("\u00e1");b["&Aacute;"]=new c("\u00c1");b["&abreve;"]=new c("\u0103");b["&Abreve;"]=new c("\u0102");b["&ac;"]=new c("\u223e");b["&acd;"]=new c("\u223f");b["&acE;"]=new c("\u223e\u0333");
b["&acirc;"]=new c("\u00e2");b["&Acirc;"]=new c("\u00c2");b["&acute;"]=new c("\u00b4");b["&acy;"]=new c("\u0430");b["&Acy;"]=new c("\u0410");b["&aelig;"]=new c("\u00e6");b["&AElig;"]=new c("\u00c6");b["&af;"]=new c("\u2061");b["&afr;"]=new c("\ud835\udd1e");b["&Afr;"]=new c("\ud835\udd04");b["&agrave;"]=new c("\u00e0");b["&Agrave;"]=new c("\u00c0");b["&aleph;"]=new c("\u2135");b["&alpha;"]=new c("\u03b1");b["&amacr;"]=new c("\u0101");b["&Amacr;"]=new c("\u0100");b["&amalg;"]=new c("\u2a3f");b["&amp;"]=
new c("&");b["&and;"]=new c("\u2227");b["&And;"]=new c("\u2a53");b["&andand;"]=new c("\u2a55");b["&andd;"]=new c("\u2a5c");b["&andslope;"]=new c("\u2a58");b["&andv;"]=new c("\u2a5a");b["&ang;"]=new c("\u2220");b["&ange;"]=new c("\u29a4");b["&angle;"]=new c("\u2220");b["&angmsd;"]=new c("\u2221");b["&angmsdaa;"]=new c("\u29a8");b["&angmsdab;"]=new c("\u29a9");b["&angmsdac;"]=new c("\u29aa");b["&angmsdad;"]=new c("\u29ab");b["&angmsdae;"]=new c("\u29ac");b["&angmsdaf;"]=new c("\u29ad");b["&angmsdag;"]=
new c("\u29ae");b["&angmsdah;"]=new c("\u29af");b["&angrt;"]=new c("\u221f");b["&angrtvb;"]=new c("\u22be");b["&angrtvbd;"]=new c("\u299d");b["&angsph;"]=new c("\u2222");b["&angst;"]=new c("\u212b");b["&angzarr;"]=new c("\u237c");b["&aogon;"]=new c("\u0105");b["&Aogon;"]=new c("\u0104");b["&aopf;"]=new c("\ud835\udd52");b["&Aopf;"]=new c("\ud835\udd38");b["&ap;"]=new c("\u2248");b["&apacir;"]=new c("\u2a6f");b["&ape;"]=new c("\u224a");b["&apE;"]=new c("\u2a70");b["&apid;"]=new c("\u224b");b["&apos;"]=
new c("'");b["&ApplyFunction;"]=new c("\u2061");b["&approx;"]=new c("\u2248");b["&approxeq;"]=new c("\u224a");b["&aring;"]=new c("\u00e5");b["&Aring;"]=new c("\u00c5");b["&ascr;"]=new c("\ud835\udcb6");b["&Ascr;"]=new c("\ud835\udc9c");b["&Assign;"]=new c("\u2254");b["&ast;"]=new c("*");b["&asymp;"]=new c("\u2248");b["&asympeq;"]=new c("\u224d");b["&atilde;"]=new c("\u00e3");b["&Atilde;"]=new c("\u00c3");b["&auml;"]=new c("\u00e4");b["&Auml;"]=new c("\u00c4");b["&awconint;"]=new c("\u2233");b["&awint;"]=
new c("\u2a11");b["&backcong;"]=new c("\u224c");b["&backepsilon;"]=new c("\u03f6");b["&backprime;"]=new c("\u2035");b["&backsim;"]=new c("\u223d");b["&backsimeq;"]=new c("\u22cd");b["&Backslash;"]=new c("\u2216");b["&Barv;"]=new c("\u2ae7");b["&barvee;"]=new c("\u22bd");b["&barwed;"]=new c("\u2305");b["&Barwed;"]=new c("\u2306");b["&barwedge;"]=new c("\u2305");b["&bbrk;"]=new c("\u23b5");b["&bbrktbrk;"]=new c("\u23b6");b["&bcong;"]=new c("\u224c");b["&bcy;"]=new c("\u0431");b["&Bcy;"]=new c("\u0411");
b["&becaus;"]=new c("\u2235");b["&because;"]=new c("\u2235");b["&Because;"]=new c("\u2235");b["&bemptyv;"]=new c("\u29b0");b["&bepsi;"]=new c("\u03f6");b["&bernou;"]=new c("\u212c");b["&Bernoullis;"]=new c("\u212c");b["&beta;"]=new c("\u03b2");b["&beth;"]=new c("\u2136");b["&between;"]=new c("\u226c");b["&bfr;"]=new c("\ud835\udd1f");b["&Bfr;"]=new c("\ud835\udd05");b["&bigcap;"]=new c("\u22c2");b["&bigcirc;"]=new c("\u25ef");b["&bigcup;"]=new c("\u22c3");b["&bigodot;"]=new c("\u2a00");b["&bigoplus;"]=
new c("\u2a01");b["&bigotimes;"]=new c("\u2a02");b["&bigsqcup;"]=new c("\u2a06");b["&bigstar;"]=new c("\u2605");b["&bigtriangledown;"]=new c("\u25bd");b["&bigtriangleup;"]=new c("\u25b3");b["&biguplus;"]=new c("\u2a04");b["&bigvee;"]=new c("\u22c1");b["&bigwedge;"]=new c("\u22c0");b["&bkarow;"]=new c("\u290d");b["&blacklozenge;"]=new c("\u29eb");b["&blacksquare;"]=new c("\u25aa");b["&blacktriangle;"]=new c("\u25b4");b["&blacktriangledown;"]=new c("\u25be");b["&blacktriangleleft;"]=new c("\u25c2");
b["&blacktriangleright;"]=new c("\u25b8");b["&blank;"]=new c("\u2423");b["&blk12;"]=new c("\u2592");b["&blk14;"]=new c("\u2591");b["&blk34;"]=new c("\u2593");b["&block;"]=new c("\u2588");b["&bne;"]=new c("=\u20e5");b["&bnequiv;"]=new c("\u2261\u20e5");b["&bnot;"]=new c("\u2310");b["&bNot;"]=new c("\u2aed");b["&bopf;"]=new c("\ud835\udd53");b["&Bopf;"]=new c("\ud835\udd39");b["&bot;"]=new c("\u22a5");b["&bottom;"]=new c("\u22a5");b["&bowtie;"]=new c("\u22c8");b["&boxbox;"]=new c("\u29c9");b["&boxdl;"]=
new c("\u2510");b["&boxdL;"]=new c("\u2555");b["&boxDl;"]=new c("\u2556");b["&boxDL;"]=new c("\u2557");b["&boxdr;"]=new c("\u250c");b["&boxdR;"]=new c("\u2552");b["&boxDr;"]=new c("\u2553");b["&boxDR;"]=new c("\u2554");b["&boxh;"]=new c("\u2500");b["&boxH;"]=new c("\u2550");b["&boxhd;"]=new c("\u252c");b["&boxhD;"]=new c("\u2565");b["&boxHd;"]=new c("\u2564");b["&boxHD;"]=new c("\u2566");b["&boxhu;"]=new c("\u2534");b["&boxhU;"]=new c("\u2568");b["&boxHu;"]=new c("\u2567");b["&boxHU;"]=new c("\u2569");
b["&boxminus;"]=new c("\u229f");b["&boxplus;"]=new c("\u229e");b["&boxtimes;"]=new c("\u22a0");b["&boxul;"]=new c("\u2518");b["&boxuL;"]=new c("\u255b");b["&boxUl;"]=new c("\u255c");b["&boxUL;"]=new c("\u255d");b["&boxur;"]=new c("\u2514");b["&boxuR;"]=new c("\u2558");b["&boxUr;"]=new c("\u2559");b["&boxUR;"]=new c("\u255a");b["&boxv;"]=new c("\u2502");b["&boxV;"]=new c("\u2551");b["&boxvh;"]=new c("\u253c");b["&boxvH;"]=new c("\u256a");b["&boxVh;"]=new c("\u256b");b["&boxVH;"]=new c("\u256c");b["&boxvl;"]=
new c("\u2524");b["&boxvL;"]=new c("\u2561");b["&boxVl;"]=new c("\u2562");b["&boxVL;"]=new c("\u2563");b["&boxvr;"]=new c("\u251c");b["&boxvR;"]=new c("\u255e");b["&boxVr;"]=new c("\u255f");b["&boxVR;"]=new c("\u2560");b["&bprime;"]=new c("\u2035");b["&breve;"]=new c("\u02d8");b["&Breve;"]=new c("\u02d8");b["&brvbar;"]=new c("\u00a6");b["&bscr;"]=new c("\ud835\udcb7");b["&Bscr;"]=new c("\u212c");b["&bsemi;"]=new c("\u204f");b["&bsim;"]=new c("\u223d");b["&bsime;"]=new c("\u22cd");b["&bsol;"]=new c("\\");
b["&bsolb;"]=new c("\u29c5");b["&bsolhsub;"]=new c("\\\u2282");b["&bull;"]=new c("\u2022");b["&bullet;"]=new c("\u2022");b["&bump;"]=new c("\u224e");b["&bumpe;"]=new c("\u224f");b["&bumpE;"]=new c("\u2aae");b["&bumpeq;"]=new c("\u224f");b["&Bumpeq;"]=new c("\u224e");b["&cacute;"]=new c("\u0107");b["&Cacute;"]=new c("\u0106");b["&cap;"]=new c("\u2229");b["&Cap;"]=new c("\u22d2");b["&capand;"]=new c("\u2a44");b["&capbrcup;"]=new c("\u2a49");b["&capcap;"]=new c("\u2a4b");b["&capcup;"]=new c("\u2a47");
b["&capdot;"]=new c("\u2a40");b["&CapitalDifferentialD;"]=new c("\u2145");b["&caps;"]=new c("\u2229\ufe00");b["&caret;"]=new c("\u2041");b["&caron;"]=new c("\u02c7");b["&Cayleys;"]=new c("\u212d");b["&ccaps;"]=new c("\u2a4d");b["&ccaron;"]=new c("\u010d");b["&Ccaron;"]=new c("\u010c");b["&ccedil;"]=new c("\u00e7");b["&Ccedil;"]=new c("\u00c7");b["&ccirc;"]=new c("\u0109");b["&Ccirc;"]=new c("\u0108");b["&Cconint;"]=new c("\u2230");b["&ccups;"]=new c("\u2a4c");b["&ccupssm;"]=new c("\u2a50");b["&cdot;"]=
new c("\u010b");b["&Cdot;"]=new c("\u010a");b["&cedil;"]=new c("\u00b8");b["&Cedilla;"]=new c("\u00b8");b["&cemptyv;"]=new c("\u29b2");b["&cent;"]=new c("\u00a2");b["&centerdot;"]=new c("\u00b7");b["&CenterDot;"]=new c("\u00b7");b["&cfr;"]=new c("\ud835\udd20");b["&Cfr;"]=new c("\u212d");b["&chcy;"]=new c("\u0447");b["&CHcy;"]=new c("\u0427");b["&check;"]=new c("\u2713");b["&checkmark;"]=new c("\u2713");b["&chi;"]=new c("\u03c7");b["&cir;"]=new c("\u25cb");b["&circ;"]=new c("\u02c6");b["&circeq;"]=
new c("\u2257");b["&circlearrowleft;"]=new c("\u21ba");b["&circlearrowright;"]=new c("\u21bb");b["&circledast;"]=new c("\u229b");b["&circledcirc;"]=new c("\u229a");b["&circleddash;"]=new c("\u229d");b["&CircleDot;"]=new c("\u2299");b["&circledR;"]=new c("\u00ae");b["&circledS;"]=new c("\u24c8");b["&CircleMinus;"]=new c("\u2296");b["&CirclePlus;"]=new c("\u2295");b["&CircleTimes;"]=new c("\u2297");b["&cire;"]=new c("\u2257");b["&cirE;"]=new c("\u29c3");b["&cirfnint;"]=new c("\u2a10");b["&cirmid;"]=
new c("\u2aef");b["&cirscir;"]=new c("\u29c2");b["&ClockwiseContourIntegral;"]=new c("\u2232");b["&CloseCurlyDoubleQuote;"]=new c("\u201d");b["&CloseCurlyQuote;"]=new c("\u2019");b["&clubs;"]=new c("\u2663");b["&clubsuit;"]=new c("\u2663");b["&colon;"]=new c(":");b["&Colon;"]=new c("\u2237");b["&colone;"]=new c("\u2254");b["&Colone;"]=new c("\u2a74");b["&coloneq;"]=new c("\u2254");b["&comma;"]=new c(",");b["&commat;"]=new c("@");b["&comp;"]=new c("\u2201");b["&compfn;"]=new c("\u2218");b["&complement;"]=
new c("\u2201");b["&complexes;"]=new c("\u2102");b["&cong;"]=new c("\u2245");b["&congdot;"]=new c("\u2a6d");b["&Congruent;"]=new c("\u2261");b["&conint;"]=new c("\u222e");b["&Conint;"]=new c("\u222f");b["&ContourIntegral;"]=new c("\u222e");b["&copf;"]=new c("\ud835\udd54");b["&Copf;"]=new c("\u2102");b["&coprod;"]=new c("\u2210");b["&Coproduct;"]=new c("\u2210");b["&copy;"]=new c("\u00a9");b["&copysr;"]=new c("\u2117");b["&CounterClockwiseContourIntegral;"]=new c("\u2233");b["&cross;"]=new c("\u2717");
b["&Cross;"]=new c("\u2a2f");b["&cscr;"]=new c("\ud835\udcb8");b["&Cscr;"]=new c("\ud835\udc9e");b["&csub;"]=new c("\u2acf");b["&csube;"]=new c("\u2ad1");b["&csup;"]=new c("\u2ad0");b["&csupe;"]=new c("\u2ad2");b["&ctdot;"]=new c("\u22ef");b["&cudarrl;"]=new c("\u2938");b["&cudarrr;"]=new c("\u2935");b["&cuepr;"]=new c("\u22de");b["&cuesc;"]=new c("\u22df");b["&cularr;"]=new c("\u21b6");b["&cularrp;"]=new c("\u293d");b["&cup;"]=new c("\u222a");b["&Cup;"]=new c("\u22d3");b["&cupbrcap;"]=new c("\u2a48");
b["&cupcap;"]=new c("\u2a46");b["&CupCap;"]=new c("\u224d");b["&cupcup;"]=new c("\u2a4a");b["&cupdot;"]=new c("\u228d");b["&cupor;"]=new c("\u2a45");b["&cups;"]=new c("\u222a\ufe00");b["&curarr;"]=new c("\u21b7");b["&curarrm;"]=new c("\u293c");b["&curlyeqprec;"]=new c("\u22de");b["&curlyeqsucc;"]=new c("\u22df");b["&curlyvee;"]=new c("\u22ce");b["&curlywedge;"]=new c("\u22cf");b["&curren;"]=new c("\u00a4");b["&curvearrowleft;"]=new c("\u21b6");b["&curvearrowright;"]=new c("\u21b7");b["&cuvee;"]=new c("\u22ce");
b["&cuwed;"]=new c("\u22cf");b["&cwconint;"]=new c("\u2232");b["&cwint;"]=new c("\u2231");b["&cylcty;"]=new c("\u232d");b["&dagger;"]=new c("\u2020");b["&Dagger;"]=new c("\u2021");b["&daleth;"]=new c("\u2138");b["&darr;"]=new c("\u2193");b["&dArr;"]=new c("\u21d3");b["&Darr;"]=new c("\u21a1");b["&dash;"]=new c("\u2010");b["&dashv;"]=new c("\u22a3");b["&Dashv;"]=new c("\u2ae4");b["&dbkarow;"]=new c("\u290f");b["&dblac;"]=new c("\u02dd");b["&dcaron;"]=new c("\u010f");b["&Dcaron;"]=new c("\u010e");b["&dcy;"]=
new c("\u0434");b["&Dcy;"]=new c("\u0414");b["&dd;"]=new c("\u2146");b["&DD;"]=new c("\u2145");b["&ddagger;"]=new c("\u2021");b["&ddarr;"]=new c("\u21ca");b["&DDotrahd;"]=new c("\u2911");b["&ddotseq;"]=new c("\u2a77");b["&deg;"]=new c("\u00b0");b["&Del;"]=new c("\u2207");b["&delta;"]=new c("\u03b4");b["&Delta;"]=new c("\u0394");b["&demptyv;"]=new c("\u29b1");b["&dfisht;"]=new c("\u297f");b["&dfr;"]=new c("\ud835\udd21");b["&Dfr;"]=new c("\ud835\udd07");b["&dHar;"]=new c("\u2965");b["&dharl;"]=new c("\u21c3");
b["&dharr;"]=new c("\u21c2");b["&DiacriticalAcute;"]=new c("\u00b4");b["&DiacriticalDot;"]=new c("\u02d9");b["&DiacriticalDoubleAcute;"]=new c("\u02dd");b["&DiacriticalGrave;"]=new c("`");b["&DiacriticalTilde;"]=new c("\u02dc");b["&diam;"]=new c("\u22c4");b["&diamond;"]=new c("\u22c4");b["&Diamond;"]=new c("\u22c4");b["&diamondsuit;"]=new c("\u2666");b["&diams;"]=new c("\u2666");b["&die;"]=new c("\u00a8");b["&DifferentialD;"]=new c("\u2146");b["&digamma;"]=new c("\u03dd");b["&disin;"]=new c("\u22f2");
b["&div;"]=new c("\u00f7");b["&divide;"]=new c("\u00f7");b["&divideontimes;"]=new c("\u22c7");b["&divonx;"]=new c("\u22c7");b["&djcy;"]=new c("\u0452");b["&DJcy;"]=new c("\u0402");b["&dlcorn;"]=new c("\u231e");b["&dlcrop;"]=new c("\u230d");b["&dollar;"]=new c("$");b["&dopf;"]=new c("\ud835\udd55");b["&Dopf;"]=new c("\ud835\udd3b");b["&dot;"]=new c("\u02d9");b["&Dot;"]=new c("\u00a8");b["&DotDot;"]=new c("\u20dc");b["&doteq;"]=new c("\u2250");b["&doteqdot;"]=new c("\u2251");b["&DotEqual;"]=new c("\u2250");
b["&dotminus;"]=new c("\u2238");b["&dotplus;"]=new c("\u2214");b["&dotsquare;"]=new c("\u22a1");b["&doublebarwedge;"]=new c("\u2306");b["&DoubleContourIntegral;"]=new c("\u222f");b["&DoubleDot;"]=new c("\u00a8");b["&DoubleDownArrow;"]=new c("\u21d3");b["&DoubleLeftArrow;"]=new c("\u21d0");b["&DoubleLeftRightArrow;"]=new c("\u21d4");b["&DoubleLeftTee;"]=new c("\u2ae4");b["&DoubleLongLeftArrow;"]=new c("\u27f8");b["&DoubleLongLeftRightArrow;"]=new c("\u27fa");b["&DoubleLongRightArrow;"]=new c("\u27f9");
b["&DoubleRightArrow;"]=new c("\u21d2");b["&DoubleRightTee;"]=new c("\u22a8");b["&DoubleUpArrow;"]=new c("\u21d1");b["&DoubleUpDownArrow;"]=new c("\u21d5");b["&DoubleVerticalBar;"]=new c("\u2225");b["&downarrow;"]=new c("\u2193");b["&Downarrow;"]=new c("\u21d3");b["&DownArrow;"]=new c("\u2193");b["&DownArrowBar;"]=new c("\u2913");b["&DownArrowUpArrow;"]=new c("\u21f5");b["&DownBreve;"]=new c("\u0311");b["&downdownarrows;"]=new c("\u21ca");b["&downharpoonleft;"]=new c("\u21c3");b["&downharpoonright;"]=
new c("\u21c2");b["&DownLeftRightVector;"]=new c("\u2950");b["&DownLeftTeeVector;"]=new c("\u295e");b["&DownLeftVector;"]=new c("\u21bd");b["&DownLeftVectorBar;"]=new c("\u2956");b["&DownRightTeeVector;"]=new c("\u295f");b["&DownRightVector;"]=new c("\u21c1");b["&DownRightVectorBar;"]=new c("\u2957");b["&DownTee;"]=new c("\u22a4");b["&DownTeeArrow;"]=new c("\u21a7");b["&drbkarow;"]=new c("\u2910");b["&drcorn;"]=new c("\u231f");b["&drcrop;"]=new c("\u230c");b["&dscr;"]=new c("\ud835\udcb9");b["&Dscr;"]=
new c("\ud835\udc9f");b["&dscy;"]=new c("\u0455");b["&DScy;"]=new c("\u0405");b["&dsol;"]=new c("\u29f6");b["&dstrok;"]=new c("\u0111");b["&Dstrok;"]=new c("\u0110");b["&dtdot;"]=new c("\u22f1");b["&dtri;"]=new c("\u25bf");b["&dtrif;"]=new c("\u25be");b["&duarr;"]=new c("\u21f5");b["&duhar;"]=new c("\u296f");b["&dwangle;"]=new c("\u29a6");b["&dzcy;"]=new c("\u045f");b["&DZcy;"]=new c("\u040f");b["&dzigrarr;"]=new c("\u27ff");b["&eacute;"]=new c("\u00e9");b["&Eacute;"]=new c("\u00c9");b["&easter;"]=
new c("\u2a6e");b["&ecaron;"]=new c("\u011b");b["&Ecaron;"]=new c("\u011a");b["&ecir;"]=new c("\u2256");b["&ecirc;"]=new c("\u00ea");b["&Ecirc;"]=new c("\u00ca");b["&ecolon;"]=new c("\u2255");b["&ecy;"]=new c("\u044d");b["&Ecy;"]=new c("\u042d");b["&eDDot;"]=new c("\u2a77");b["&edot;"]=new c("\u0117");b["&eDot;"]=new c("\u2251");b["&Edot;"]=new c("\u0116");b["&ee;"]=new c("\u2147");b["&efDot;"]=new c("\u2252");b["&efr;"]=new c("\ud835\udd22");b["&Efr;"]=new c("\ud835\udd08");b["&eg;"]=new c("\u2a9a");
b["&egrave;"]=new c("\u00e8");b["&Egrave;"]=new c("\u00c8");b["&egs;"]=new c("\u2a96");b["&egsdot;"]=new c("\u2a98");b["&el;"]=new c("\u2a99");b["&Element;"]=new c("\u2208");b["&elinters;"]=new c("\ufffd");b["&ell;"]=new c("\u2113");b["&els;"]=new c("\u2a95");b["&elsdot;"]=new c("\u2a97");b["&emacr;"]=new c("\u0113");b["&Emacr;"]=new c("\u0112");b["&empty;"]=new c("\u2205");b["&emptyset;"]=new c("\u2205");b["&EmptySmallSquare;"]=new c("\u25fb");b["&emptyv;"]=new c("\u2205");b["&EmptyVerySmallSquare;"]=
new c("\u25ab");b["&emsp;"]=new c("\u2003");b["&emsp13;"]=new c("\u2004");b["&emsp14;"]=new c("\u2005");b["&eng;"]=new c("\u014b");b["&ENG;"]=new c("\u014a");b["&ensp;"]=new c("\u2002");b["&eogon;"]=new c("\u0119");b["&Eogon;"]=new c("\u0118");b["&eopf;"]=new c("\ud835\udd56");b["&Eopf;"]=new c("\ud835\udd3c");b["&epar;"]=new c("\u22d5");b["&eparsl;"]=new c("\u29e3");b["&eplus;"]=new c("\u2a71");b["&epsi;"]=new c("\u03f5");b["&epsiv;"]=new c("\u03b5");b["&eqcirc;"]=new c("\u2256");b["&eqcolon;"]=
new c("\u2255");b["&eqsim;"]=new c("\u2242");b["&eqslantgtr;"]=new c("\u2a96");b["&eqslantless;"]=new c("\u2a95");b["&Equal;"]=new c("\u2a75");b["&equals;"]=new c("=");b["&EqualTilde;"]=new c("\u2242");b["&equest;"]=new c("\u225f");b["&Equilibrium;"]=new c("\u21cc");b["&equiv;"]=new c("\u2261");b["&equivDD;"]=new c("\u2a78");b["&eqvparsl;"]=new c("\u29e5");b["&erarr;"]=new c("\u2971");b["&erDot;"]=new c("\u2253");b["&escr;"]=new c("\u212f");b["&Escr;"]=new c("\u2130");b["&esdot;"]=new c("\u2250");
b["&esim;"]=new c("\u2242");b["&Esim;"]=new c("\u2a73");b["&eta;"]=new c("\u03b7");b["&eth;"]=new c("\u00f0");b["&ETH;"]=new c("\u00d0");b["&euml;"]=new c("\u00eb");b["&Euml;"]=new c("\u00cb");b["&excl;"]=new c("!");b["&exist;"]=new c("\u2203");b["&Exists;"]=new c("\u2203");b["&expectation;"]=new c("\u2130");b["&exponentiale;"]=new c("\u2147");b["&ExponentialE;"]=new c("\u2147");b["&fallingdotseq;"]=new c("\u2252");b["&fcy;"]=new c("\u0444");b["&Fcy;"]=new c("\u0424");b["&female;"]=new c("\u2640");
b["&ffilig;"]=new c("\ufb03");b["&fflig;"]=new c("\ufb00");b["&ffllig;"]=new c("\ufb04");b["&ffr;"]=new c("\ud835\udd23");b["&Ffr;"]=new c("\ud835\udd09");b["&filig;"]=new c("\ufb01");b["&FilledSmallSquare;"]=new c("\u25fc");b["&FilledVerySmallSquare;"]=new c("\u25aa");b["&flat;"]=new c("\u266d");b["&fllig;"]=new c("\ufb02");b["&fltns;"]=new c("\u25b1");b["&fnof;"]=new c("\u0192");b["&fopf;"]=new c("\ud835\udd57");b["&Fopf;"]=new c("\ud835\udd3d");b["&forall;"]=new c("\u2200");b["&ForAll;"]=new c("\u2200");
b["&fork;"]=new c("\u22d4");b["&forkv;"]=new c("\u2ad9");b["&Fouriertrf;"]=new c("\u2131");b["&fpartint;"]=new c("\u2a0d");b["&frac12;"]=new c("\u00bd");b["&frac13;"]=new c("\u2153");b["&frac14;"]=new c("\u00bc");b["&frac15;"]=new c("\u2155");b["&frac16;"]=new c("\u2159");b["&frac18;"]=new c("\u215b");b["&frac23;"]=new c("\u2154");b["&frac25;"]=new c("\u2156");b["&frac34;"]=new c("\u00be");b["&frac35;"]=new c("\u2157");b["&frac38;"]=new c("\u215c");b["&frac45;"]=new c("\u2158");b["&frac56;"]=new c("\u215a");
b["&frac58;"]=new c("\u215d");b["&frac78;"]=new c("\u215e");b["&frown;"]=new c("\u2322");b["&fscr;"]=new c("\ud835\udcbb");b["&Fscr;"]=new c("\u2131");b["&gacute;"]=new c("\u01f5");b["&gamma;"]=new c("\u03b3");b["&Gamma;"]=new c("\u0393");b["&gammad;"]=new c("\u03dd");b["&Gammad;"]=new c("\u03dc");b["&gap;"]=new c("\u2a86");b["&gbreve;"]=new c("\u011f");b["&Gbreve;"]=new c("\u011e");b["&Gcedil;"]=new c("\u0122");b["&gcirc;"]=new c("\u011d");b["&Gcirc;"]=new c("\u011c");b["&gcy;"]=new c("\u0433");
b["&Gcy;"]=new c("\u0413");b["&gdot;"]=new c("\u0121");b["&Gdot;"]=new c("\u0120");b["&ge;"]=new c("\u2265");b["&gE;"]=new c("\u2267");b["&gel;"]=new c("\u22db");b["&gEl;"]=new c("\u2a8c");b["&geq;"]=new c("\u2265");b["&geqq;"]=new c("\u2267");b["&geqslant;"]=new c("\u2a7e");b["&ges;"]=new c("\u2a7e");b["&gescc;"]=new c("\u2aa9");b["&gesdot;"]=new c("\u2a80");b["&gesdoto;"]=new c("\u2a82");b["&gesdotol;"]=new c("\u2a84");b["&gesl;"]=new c("\u22db\ufe00");b["&gesles;"]=new c("\u2a94");b["&gfr;"]=new c("\ud835\udd24");
b["&Gfr;"]=new c("\ud835\udd0a");b["&gg;"]=new c("\u226b");b["&Gg;"]=new c("\u22d9");b["&ggg;"]=new c("\u22d9");b["&gimel;"]=new c("\u2137");b["&gjcy;"]=new c("\u0453");b["&GJcy;"]=new c("\u0403");b["&gl;"]=new c("\u2277");b["&gla;"]=new c("\u2aa5");b["&glE;"]=new c("\u2a92");b["&glj;"]=new c("\u2aa4");b["&gnap;"]=new c("\u2a8a");b["&gnapprox;"]=new c("\u2a8a");b["&gne;"]=new c("\u2a88");b["&gnE;"]=new c("\u2269");b["&gneq;"]=new c("\u2a88");b["&gneqq;"]=new c("\u2269");b["&gnsim;"]=new c("\u22e7");
b["&gopf;"]=new c("\ud835\udd58");b["&Gopf;"]=new c("\ud835\udd3e");b["&grave;"]=new c("`");b["&GreaterEqual;"]=new c("\u2265");b["&GreaterEqualLess;"]=new c("\u22db");b["&GreaterFullEqual;"]=new c("\u2267");b["&GreaterGreater;"]=new c("\u2aa2");b["&GreaterLess;"]=new c("\u2277");b["&GreaterSlantEqual;"]=new c("\u2a7e");b["&GreaterTilde;"]=new c("\u2273");b["&gscr;"]=new c("\u210a");b["&Gscr;"]=new c("\ud835\udca2");b["&gsim;"]=new c("\u2273");b["&gsime;"]=new c("\u2a8e");b["&gsiml;"]=new c("\u2a90");
b["&gt;"]=new c(">");b["&Gt;"]=new c("\u226b");b["&gtcc;"]=new c("\u2aa7");b["&gtcir;"]=new c("\u2a7a");b["&gtdot;"]=new c("\u22d7");b["&gtlPar;"]=new c("\u2995");b["&gtquest;"]=new c("\u2a7c");b["&gtrapprox;"]=new c("\u2a86");b["&gtrarr;"]=new c("\u2978");b["&gtrdot;"]=new c("\u22d7");b["&gtreqless;"]=new c("\u22db");b["&gtreqqless;"]=new c("\u2a8c");b["&gtrless;"]=new c("\u2277");b["&gtrsim;"]=new c("\u2273");b["&gvertneqq;"]=new c("\u2269\ufe00");b["&gvnE;"]=new c("\u2269\ufe00");b["&Hacek;"]=
new c("\u02c7");b["&hairsp;"]=new c("\u200a");b["&half;"]=new c("\u00bd");b["&hamilt;"]=new c("\u210b");b["&hardcy;"]=new c("\u044a");b["&HARDcy;"]=new c("\u042a");b["&harr;"]=new c("\u2194");b["&hArr;"]=new c("\u21d4");b["&harrcir;"]=new c("\u2948");b["&harrw;"]=new c("\u21ad");b["&Hat;"]=new c("^");b["&hbar;"]=new c("\u210f");b["&hcirc;"]=new c("\u0125");b["&Hcirc;"]=new c("\u0124");b["&hearts;"]=new c("\u2665");b["&heartsuit;"]=new c("\u2665");b["&hellip;"]=new c("\u2026");b["&hercon;"]=new c("\u22b9");
b["&hfr;"]=new c("\ud835\udd25");b["&Hfr;"]=new c("\u210c");b["&HilbertSpace;"]=new c("\u210b");b["&hksearow;"]=new c("\u2925");b["&hkswarow;"]=new c("\u2926");b["&hoarr;"]=new c("\u21ff");b["&homtht;"]=new c("\u223b");b["&hookleftarrow;"]=new c("\u21a9");b["&hookrightarrow;"]=new c("\u21aa");b["&hopf;"]=new c("\ud835\udd59");b["&Hopf;"]=new c("\u210d");b["&horbar;"]=new c("\u2015");b["&HorizontalLine;"]=new c("\u2500");b["&hscr;"]=new c("\ud835\udcbd");b["&Hscr;"]=new c("\u210b");b["&hslash;"]=new c("\u210f");
b["&hstrok;"]=new c("\u0127");b["&Hstrok;"]=new c("\u0126");b["&HumpDownHump;"]=new c("\u224e");b["&HumpEqual;"]=new c("\u224f");b["&hybull;"]=new c("\u2043");b["&hyphen;"]=new c("\u2010");b["&iacute;"]=new c("\u00ed");b["&Iacute;"]=new c("\u00cd");b["&ic;"]=new c("\u2063");b["&icirc;"]=new c("\u00ee");b["&Icirc;"]=new c("\u00ce");b["&icy;"]=new c("\u0438");b["&Icy;"]=new c("\u0418");b["&Idot;"]=new c("\u0130");b["&iecy;"]=new c("\u0435");b["&IEcy;"]=new c("\u0415");b["&iexcl;"]=new c("\u00a1");b["&iff;"]=
new c("\u21d4");b["&ifr;"]=new c("\ud835\udd26");b["&Ifr;"]=new c("\u2111");b["&igrave;"]=new c("\u00ec");b["&Igrave;"]=new c("\u00cc");b["&ii;"]=new c("\u2148");b["&iiiint;"]=new c("\u2a0c");b["&iiint;"]=new c("\u222d");b["&iinfin;"]=new c("\u29dc");b["&iiota;"]=new c("\u2129");b["&ijlig;"]=new c("\u0133");b["&IJlig;"]=new c("\u0132");b["&Im;"]=new c("\u2111");b["&imacr;"]=new c("\u012b");b["&Imacr;"]=new c("\u012a");b["&image;"]=new c("\u2111");b["&ImaginaryI;"]=new c("\u2148");b["&imagline;"]=
new c("\u2110");b["&imagpart;"]=new c("\u2111");b["&imath;"]=new c("\u0131");b["&imof;"]=new c("\u22b7");b["&imped;"]=new c("\u01b5");b["&Implies;"]=new c("\u21d2");b["&in;"]=new c("\u2208");b["&incare;"]=new c("\u2105");b["&infin;"]=new c("\u221e");b["&infintie;"]=new c("\u29dd");b["&inodot;"]=new c("\u0131");b["&int;"]=new c("\u222b");b["&Int;"]=new c("\u222c");b["&intcal;"]=new c("\u22ba");b["&integers;"]=new c("\u2124");b["&Integral;"]=new c("\u222b");b["&intercal;"]=new c("\u22ba");b["&Intersection;"]=
new c("\u22c2");b["&intlarhk;"]=new c("\u2a17");b["&intprod;"]=new c("\u2a3c");b["&InvisibleComma;"]=new c("\u2063");b["&InvisibleTimes;"]=new c("\u2062");b["&iocy;"]=new c("\u0451");b["&IOcy;"]=new c("\u0401");b["&iogon;"]=new c("\u012f");b["&Iogon;"]=new c("\u012e");b["&iopf;"]=new c("\ud835\udd5a");b["&Iopf;"]=new c("\ud835\udd40");b["&iota;"]=new c("\u03b9");b["&iprod;"]=new c("\u2a3c");b["&iquest;"]=new c("\u00bf");b["&iscr;"]=new c("\ud835\udcbe");b["&Iscr;"]=new c("\u2110");b["&isin;"]=new c("\u2208");
b["&isindot;"]=new c("\u22f5");b["&isinE;"]=new c("\u22f9");b["&isins;"]=new c("\u22f4");b["&isinsv;"]=new c("\u22f3");b["&isinv;"]=new c("\u2208");b["&it;"]=new c("\u2062");b["&itilde;"]=new c("\u0129");b["&Itilde;"]=new c("\u0128");b["&iukcy;"]=new c("\u0456");b["&Iukcy;"]=new c("\u0406");b["&iuml;"]=new c("\u00ef");b["&Iuml;"]=new c("\u00cf");b["&jcirc;"]=new c("\u0135");b["&Jcirc;"]=new c("\u0134");b["&jcy;"]=new c("\u0439");b["&Jcy;"]=new c("\u0419");b["&jfr;"]=new c("\ud835\udd27");b["&Jfr;"]=
new c("\ud835\udd0d");b["&jmath;"]=new c("j");b["&jopf;"]=new c("\ud835\udd5b");b["&Jopf;"]=new c("\ud835\udd41");b["&jscr;"]=new c("\ud835\udcbf");b["&Jscr;"]=new c("\ud835\udca5");b["&jsercy;"]=new c("\u0458");b["&Jsercy;"]=new c("\u0408");b["&jukcy;"]=new c("\u0454");b["&Jukcy;"]=new c("\u0404");b["&kappa;"]=new c("\u03ba");b["&kappav;"]=new c("\u03f0");b["&kcedil;"]=new c("\u0137");b["&Kcedil;"]=new c("\u0136");b["&kcy;"]=new c("\u043a");b["&Kcy;"]=new c("\u041a");b["&kfr;"]=new c("\ud835\udd28");
b["&Kfr;"]=new c("\ud835\udd0e");b["&kgreen;"]=new c("\u0138");b["&khcy;"]=new c("\u0445");b["&KHcy;"]=new c("\u0425");b["&kjcy;"]=new c("\u045c");b["&KJcy;"]=new c("\u040c");b["&kopf;"]=new c("\ud835\udd5c");b["&Kopf;"]=new c("\ud835\udd42");b["&kscr;"]=new c("\ud835\udcc0");b["&Kscr;"]=new c("\ud835\udca6");b["&lAarr;"]=new c("\u21da");b["&lacute;"]=new c("\u013a");b["&Lacute;"]=new c("\u0139");b["&laemptyv;"]=new c("\u29b4");b["&lagran;"]=new c("\u2112");b["&lambda;"]=new c("\u03bb");b["&Lambda;"]=
new c("\u039b");b["&lang;"]=new c("\u2329");b["&Lang;"]=new c("\u300a");b["&langd;"]=new c("\u2991");b["&langle;"]=new c("\u2329");b["&lap;"]=new c("\u2a85");b["&Laplacetrf;"]=new c("\u2112");b["&laquo;"]=new c("\u00ab");b["&larr;"]=new c("\u2190");b["&lArr;"]=new c("\u21d0");b["&Larr;"]=new c("\u219e");b["&larrb;"]=new c("\u21e4");b["&larrbfs;"]=new c("\u291f");b["&larrfs;"]=new c("\u291d");b["&larrhk;"]=new c("\u21a9");b["&larrlp;"]=new c("\u21ab");b["&larrpl;"]=new c("\u2939");b["&larrsim;"]=new c("\u2973");
b["&larrtl;"]=new c("\u21a2");b["&lat;"]=new c("\u2aab");b["&latail;"]=new c("\u2919");b["&lAtail;"]=new c("\u291b");b["&late;"]=new c("\u2aad");b["&lates;"]=new c("\u2aad\ufe00");b["&lbarr;"]=new c("\u290c");b["&lBarr;"]=new c("\u290e");b["&lbbrk;"]=new c("\u3014");b["&lbrace;"]=new c("{");b["&lbrack;"]=new c("[");b["&lbrke;"]=new c("\u298b");b["&lbrksld;"]=new c("\u298f");b["&lbrkslu;"]=new c("\u298d");b["&lcaron;"]=new c("\u013e");b["&Lcaron;"]=new c("\u013d");b["&lcedil;"]=new c("\u013c");b["&Lcedil;"]=
new c("\u013b");b["&lceil;"]=new c("\u2308");b["&lcub;"]=new c("{");b["&lcy;"]=new c("\u043b");b["&Lcy;"]=new c("\u041b");b["&ldca;"]=new c("\u2936");b["&ldquo;"]=new c("\u201c");b["&ldquor;"]=new c("\u201e");b["&ldrdhar;"]=new c("\u2967");b["&ldrushar;"]=new c("\u294b");b["&ldsh;"]=new c("\u21b2");b["&le;"]=new c("\u2264");b["&lE;"]=new c("\u2266");b["&LeftAngleBracket;"]=new c("\u2329");b["&leftarrow;"]=new c("\u2190");b["&Leftarrow;"]=new c("\u21d0");b["&LeftArrow;"]=new c("\u2190");b["&LeftArrowBar;"]=
new c("\u21e4");b["&LeftArrowRightArrow;"]=new c("\u21c6");b["&leftarrowtail;"]=new c("\u21a2");b["&LeftCeiling;"]=new c("\u2308");b["&LeftDoubleBracket;"]=new c("\u301a");b["&LeftDownTeeVector;"]=new c("\u2961");b["&LeftDownVector;"]=new c("\u21c3");b["&LeftDownVectorBar;"]=new c("\u2959");b["&LeftFloor;"]=new c("\u230a");b["&leftharpoondown;"]=new c("\u21bd");b["&leftharpoonup;"]=new c("\u21bc");b["&leftleftarrows;"]=new c("\u21c7");b["&leftrightarrow;"]=new c("\u2194");b["&Leftrightarrow;"]=new c("\u21d4");
b["&LeftRightArrow;"]=new c("\u2194");b["&leftrightarrows;"]=new c("\u21c6");b["&leftrightharpoons;"]=new c("\u21cb");b["&leftrightsquigarrow;"]=new c("\u21ad");b["&LeftRightVector;"]=new c("\u294e");b["&LeftTee;"]=new c("\u22a3");b["&LeftTeeArrow;"]=new c("\u21a4");b["&LeftTeeVector;"]=new c("\u295a");b["&leftthreetimes;"]=new c("\u22cb");b["&LeftTriangle;"]=new c("\u22b2");b["&LeftTriangleBar;"]=new c("\u29cf");b["&LeftTriangleEqual;"]=new c("\u22b4");b["&LeftUpDownVector;"]=new c("\u2951");b["&LeftUpTeeVector;"]=
new c("\u2960");b["&LeftUpVector;"]=new c("\u21bf");b["&LeftUpVectorBar;"]=new c("\u2958");b["&LeftVector;"]=new c("\u21bc");b["&LeftVectorBar;"]=new c("\u2952");b["&leg;"]=new c("\u22da");b["&lEg;"]=new c("\u2a8b");b["&leq;"]=new c("\u2264");b["&leqq;"]=new c("\u2266");b["&leqslant;"]=new c("\u2a7d");b["&les;"]=new c("\u2a7d");b["&lescc;"]=new c("\u2aa8");b["&lesdot;"]=new c("\u2a7f");b["&lesdoto;"]=new c("\u2a81");b["&lesdotor;"]=new c("\u2a83");b["&lesg;"]=new c("\u22da\ufe00");b["&lesges;"]=new c("\u2a93");
b["&lessapprox;"]=new c("\u2a85");b["&lessdot;"]=new c("\u22d6");b["&lesseqgtr;"]=new c("\u22da");b["&lesseqqgtr;"]=new c("\u2a8b");b["&LessEqualGreater;"]=new c("\u22da");b["&LessFullEqual;"]=new c("\u2266");b["&LessGreater;"]=new c("\u2276");b["&lessgtr;"]=new c("\u2276");b["&LessLess;"]=new c("\u2aa1");b["&lesssim;"]=new c("\u2272");b["&LessSlantEqual;"]=new c("\u2a7d");b["&LessTilde;"]=new c("\u2272");b["&lfisht;"]=new c("\u297c");b["&lfloor;"]=new c("\u230a");b["&lfr;"]=new c("\ud835\udd29");
b["&Lfr;"]=new c("\ud835\udd0f");b["&lg;"]=new c("\u2276");b["&lgE;"]=new c("\u2a91");b["&lHar;"]=new c("\u2962");b["&lhard;"]=new c("\u21bd");b["&lharu;"]=new c("\u21bc");b["&lharul;"]=new c("\u296a");b["&lhblk;"]=new c("\u2584");b["&ljcy;"]=new c("\u0459");b["&LJcy;"]=new c("\u0409");b["&ll;"]=new c("\u226a");b["&Ll;"]=new c("\u22d8");b["&llarr;"]=new c("\u21c7");b["&llcorner;"]=new c("\u231e");b["&Lleftarrow;"]=new c("\u21da");b["&llhard;"]=new c("\u296b");b["&lltri;"]=new c("\u25fa");b["&lmidot;"]=
new c("\u0140");b["&Lmidot;"]=new c("\u013f");b["&lmoust;"]=new c("\u23b0");b["&lmoustache;"]=new c("\u23b0");b["&lnap;"]=new c("\u2a89");b["&lnapprox;"]=new c("\u2a89");b["&lne;"]=new c("\u2a87");b["&lnE;"]=new c("\u2268");b["&lneq;"]=new c("\u2a87");b["&lneqq;"]=new c("\u2268");b["&lnsim;"]=new c("\u22e6");b["&loang;"]=new c("\u3018");b["&loarr;"]=new c("\u21fd");b["&lobrk;"]=new c("\u301a");b["&longleftarrow;"]=new c("\u27f5");b["&Longleftarrow;"]=new c("\u27f8");b["&LongLeftArrow;"]=new c("\u27f5");
b["&longleftrightarrow;"]=new c("\u27f7");b["&Longleftrightarrow;"]=new c("\u27fa");b["&LongLeftRightArrow;"]=new c("\u27f7");b["&longmapsto;"]=new c("\u27fc");b["&longrightarrow;"]=new c("\u27f6");b["&Longrightarrow;"]=new c("\u27f9");b["&LongRightArrow;"]=new c("\u27f6");b["&looparrowleft;"]=new c("\u21ab");b["&looparrowright;"]=new c("\u21ac");b["&lopar;"]=new c("\u2985");b["&lopf;"]=new c("\ud835\udd5d");b["&Lopf;"]=new c("\ud835\udd43");b["&loplus;"]=new c("\u2a2d");b["&lotimes;"]=new c("\u2a34");
b["&lowast;"]=new c("\u2217");b["&lowbar;"]=new c("_");b["&LowerLeftArrow;"]=new c("\u2199");b["&LowerRightArrow;"]=new c("\u2198");b["&loz;"]=new c("\u25ca");b["&lozenge;"]=new c("\u25ca");b["&lozf;"]=new c("\u29eb");b["&lpar;"]=new c("(");b["&lparlt;"]=new c("\u2993");b["&lrarr;"]=new c("\u21c6");b["&lrcorner;"]=new c("\u231f");b["&lrhar;"]=new c("\u21cb");b["&lrhard;"]=new c("\u296d");b["&lrtri;"]=new c("\u22bf");b["&lscr;"]=new c("\ud835\udcc1");b["&Lscr;"]=new c("\u2112");b["&lsh;"]=new c("\u21b0");
b["&Lsh;"]=new c("\u21b0");b["&lsim;"]=new c("\u2272");b["&lsime;"]=new c("\u2a8d");b["&lsimg;"]=new c("\u2a8f");b["&lsqb;"]=new c("[");b["&lsquo;"]=new c("\u2018");b["&lsquor;"]=new c("\u201a");b["&lstrok;"]=new c("\u0142");b["&Lstrok;"]=new c("\u0141");b["&lt;"]=new c("<");b["&Lt;"]=new c("\u226a");b["&ltcc;"]=new c("\u2aa6");b["&ltcir;"]=new c("\u2a79");b["&ltdot;"]=new c("\u22d6");b["&lthree;"]=new c("\u22cb");b["&ltimes;"]=new c("\u22c9");b["&ltlarr;"]=new c("\u2976");b["&ltquest;"]=new c("\u2a7b");
b["&ltri;"]=new c("\u25c3");b["&ltrie;"]=new c("\u22b4");b["&ltrif;"]=new c("\u25c2");b["&ltrPar;"]=new c("\u2996");b["&lurdshar;"]=new c("\u294a");b["&luruhar;"]=new c("\u2966");b["&lvertneqq;"]=new c("\u2268\ufe00");b["&lvnE;"]=new c("\u2268\ufe00");b["&macr;"]=new c("\u00af");b["&male;"]=new c("\u2642");b["&malt;"]=new c("\u2720");b["&maltese;"]=new c("\u2720");b["&map;"]=new c("\u21a6");b["&Map;"]=new c("\u2905");b["&mapsto;"]=new c("\u21a6");b["&mapstodown;"]=new c("\u21a7");b["&mapstoleft;"]=
new c("\u21a4");b["&mapstoup;"]=new c("\u21a5");b["&marker;"]=new c("\u25ae");b["&mcomma;"]=new c("\u2a29");b["&mcy;"]=new c("\u043c");b["&Mcy;"]=new c("\u041c");b["&mdash;"]=new c("\u2014");b["&mDDot;"]=new c("\u223a");b["&measuredangle;"]=new c("\u2221");b["&MediumSpace;"]=new c("\u205f");b["&Mellintrf;"]=new c("\u2133");b["&mfr;"]=new c("\ud835\udd2a");b["&Mfr;"]=new c("\ud835\udd10");b["&mho;"]=new c("\u2127");b["&micro;"]=new c("\u00b5");b["&mid;"]=new c("\u2223");b["&midast;"]=new c("*");b["&midcir;"]=
new c("\u2af0");b["&middot;"]=new c("\u00b7");b["&minus;"]=new c("\u2212");b["&minusb;"]=new c("\u229f");b["&minusd;"]=new c("\u2238");b["&minusdu;"]=new c("\u2a2a");b["&MinusPlus;"]=new c("\u2213");b["&mlcp;"]=new c("\u2adb");b["&mldr;"]=new c("\u2026");b["&mnplus;"]=new c("\u2213");b["&models;"]=new c("\u22a7");b["&mopf;"]=new c("\ud835\udd5e");b["&Mopf;"]=new c("\ud835\udd44");b["&mp;"]=new c("\u2213");b["&mscr;"]=new c("\ud835\udcc2");b["&Mscr;"]=new c("\u2133");b["&mstpos;"]=new c("\u223e");
b["&mu;"]=new c("\u03bc");b["&multimap;"]=new c("\u22b8");b["&mumap;"]=new c("\u22b8");b["&nabla;"]=new c("\u2207");b["&nacute;"]=new c("\u0144");b["&Nacute;"]=new c("\u0143");b["&nang;"]=new c("\u2220\u20d2");b["&nap;"]=new c("\u2249");b["&napE;"]=new c("\u2a70\u0338");b["&napid;"]=new c("\u224b\u0338");b["&napos;"]=new c("\u0149");b["&napprox;"]=new c("\u2249");b["&natur;"]=new c("\u266e");b["&natural;"]=new c("\u266e");b["&naturals;"]=new c("\u2115");b["&nbsp;"]=new c("\u00a0");b["&nbump;"]=new c("\u224e\u0338");
b["&nbumpe;"]=new c("\u224f\u0338");b["&ncap;"]=new c("\u2a43");b["&ncaron;"]=new c("\u0148");b["&Ncaron;"]=new c("\u0147");b["&ncedil;"]=new c("\u0146");b["&Ncedil;"]=new c("\u0145");b["&ncong;"]=new c("\u2247");b["&ncongdot;"]=new c("\u2a6d\u0338");b["&ncup;"]=new c("\u2a42");b["&ncy;"]=new c("\u043d");b["&Ncy;"]=new c("\u041d");b["&ndash;"]=new c("\u2013");b["&ne;"]=new c("\u2260");b["&nearhk;"]=new c("\u2924");b["&nearr;"]=new c("\u2197");b["&neArr;"]=new c("\u21d7");b["&nearrow;"]=new c("\u2197");
b["&nedot;"]=new c("\u2250\u0338");b["&NegativeMediumSpace;"]=new c("\u200b");b["&NegativeThickSpace;"]=new c("\u200b");b["&NegativeThinSpace;"]=new c("\u200b");b["&NegativeVeryThinSpace;"]=new c("\u200b");b["&nequiv;"]=new c("\u2262");b["&nesear;"]=new c("\u2928");b["&nesim;"]=new c("\u2242\u0338");b["&NestedGreaterGreater;"]=new c("\u226b");b["&NestedLessLess;"]=new c("\u226a");b["&NewLine;"]=new c("\n");b["&nexist;"]=new c("\u2204");b["&nexists;"]=new c("\u2204");b["&nfr;"]=new c("\ud835\udd2b");
b["&Nfr;"]=new c("\ud835\udd11");b["&nge;"]=new c("\u2271");b["&ngE;"]=new c("\u2267\u0338");b["&ngeq;"]=new c("\u2271");b["&ngeqq;"]=new c("\u2267\u0338");b["&ngeqslant;"]=new c("\u2a7e\u0338");b["&nges;"]=new c("\u2a7e\u0338");b["&nGg;"]=new c("\u22d9\u0338");b["&ngsim;"]=new c("\u2275");b["&ngt;"]=new c("\u226f");b["&nGt;"]=new c("\u226b\u20d2");b["&ngtr;"]=new c("\u226f");b["&nGtv;"]=new c("\u226b\u0338");b["&nharr;"]=new c("\u21ae");b["&nhArr;"]=new c("\u21ce");b["&nhpar;"]=new c("\u2af2");b["&ni;"]=
new c("\u220b");b["&nis;"]=new c("\u22fc");b["&nisd;"]=new c("\u22fa");b["&niv;"]=new c("\u220b");b["&njcy;"]=new c("\u045a");b["&NJcy;"]=new c("\u040a");b["&nlarr;"]=new c("\u219a");b["&nlArr;"]=new c("\u21cd");b["&nldr;"]=new c("\u2025");b["&nle;"]=new c("\u2270");b["&nlE;"]=new c("\u2266\u0338");b["&nleftarrow;"]=new c("\u219a");b["&nLeftarrow;"]=new c("\u21cd");b["&nleftrightarrow;"]=new c("\u21ae");b["&nLeftrightarrow;"]=new c("\u21ce");b["&nleq;"]=new c("\u2270");b["&nleqq;"]=new c("\u2266\u0338");
b["&nleqslant;"]=new c("\u2a7d\u0338");b["&nles;"]=new c("\u2a7d\u0338");b["&nless;"]=new c("\u226e");b["&nLl;"]=new c("\u22d8\u0338");b["&nlsim;"]=new c("\u2274");b["&nlt;"]=new c("\u226e");b["&nLt;"]=new c("\u226a\u20d2");b["&nltri;"]=new c("\u22ea");b["&nltrie;"]=new c("\u22ec");b["&nLtv;"]=new c("\u226a\u0338");b["&nmid;"]=new c("\u2224");b["&NoBreak;"]=new c("\u2060");b["&NonBreakingSpace;"]=new c("\u00a0");b["&nopf;"]=new c("\ud835\udd5f");b["&Nopf;"]=new c("\u2115");b["&not;"]=new c("\u00ac");
b["&Not;"]=new c("\u2aec");b["&NotCongruent;"]=new c("\u2262");b["&NotCupCap;"]=new c("\u226d");b["&NotDoubleVerticalBar;"]=new c("\u2226");b["&NotElement;"]=new c("\u2209");b["&NotEqual;"]=new c("\u2260");b["&NotEqualTilde;"]=new c("\u2242\u0338");b["&NotExists;"]=new c("\u2204");b["&NotGreater;"]=new c("\u226f");b["&NotGreaterEqual;"]=new c("\u2271");b["&NotGreaterFullEqual;"]=new c("\u2266\u0338");b["&NotGreaterGreater;"]=new c("\u226b\u0338");b["&NotGreaterLess;"]=new c("\u2279");b["&NotGreaterSlantEqual;"]=
new c("\u2a7e\u0338");b["&NotGreaterTilde;"]=new c("\u2275");b["&NotHumpDownHump;"]=new c("\u224e\u0338");b["&NotHumpEqual;"]=new c("\u224f\u0338");b["&notin;"]=new c("\u2209");b["&notindot;"]=new c("\u22f5\u0338");b["&notinE;"]=new c("\u22f9\u0338");b["&notinva;"]=new c("\u2209");b["&notinvb;"]=new c("\u22f7");b["&notinvc;"]=new c("\u22f6");b["&NotLeftTriangle;"]=new c("\u22ea");b["&NotLeftTriangleBar;"]=new c("\u29cf\u0338");b["&NotLeftTriangleEqual;"]=new c("\u22ec");b["&NotLess;"]=new c("\u226e");
b["&NotLessEqual;"]=new c("\u2270");b["&NotLessGreater;"]=new c("\u2278");b["&NotLessLess;"]=new c("\u226a\u0338");b["&NotLessSlantEqual;"]=new c("\u2a7d\u0338");b["&NotLessTilde;"]=new c("\u2274");b["&NotNestedGreaterGreater;"]=new c("\u2aa2\u0338");b["&NotNestedLessLess;"]=new c("\u2aa1\u0338");b["&notni;"]=new c("\u220c");b["&notniva;"]=new c("\u220c");b["&notnivb;"]=new c("\u22fe");b["&notnivc;"]=new c("\u22fd");b["&NotPrecedes;"]=new c("\u2280");b["&NotPrecedesEqual;"]=new c("\u2aaf\u0338");
b["&NotPrecedesSlantEqual;"]=new c("\u22e0");b["&NotReverseElement;"]=new c("\u220c");b["&NotRightTriangle;"]=new c("\u22eb");b["&NotRightTriangleBar;"]=new c("\u29d0\u0338");b["&NotRightTriangleEqual;"]=new c("\u22ed");b["&NotSquareSubset;"]=new c("\u228f\u0338");b["&NotSquareSubsetEqual;"]=new c("\u22e2");b["&NotSquareSuperset;"]=new c("\u2290\u0338");b["&NotSquareSupersetEqual;"]=new c("\u22e3");b["&NotSubset;"]=new c("\u2282\u20d2");b["&NotSubsetEqual;"]=new c("\u2288");b["&NotSucceeds;"]=new c("\u2281");
b["&NotSucceedsEqual;"]=new c("\u2ab0\u0338");b["&NotSucceedsSlantEqual;"]=new c("\u22e1");b["&NotSucceedsTilde;"]=new c("\u227f\u0338");b["&NotSuperset;"]=new c("\u2283\u20d2");b["&NotSupersetEqual;"]=new c("\u2289");b["&NotTilde;"]=new c("\u2241");b["&NotTildeEqual;"]=new c("\u2244");b["&NotTildeFullEqual;"]=new c("\u2247");b["&NotTildeTilde;"]=new c("\u2249");b["&NotVerticalBar;"]=new c("\u2224");b["&npar;"]=new c("\u2226");b["&nparallel;"]=new c("\u2226");b["&nparsl;"]=new c("\u2afd\u20e5");b["&npart;"]=
new c("\u2202\u0338");b["&npolint;"]=new c("\u2a14");b["&npr;"]=new c("\u2280");b["&nprcue;"]=new c("\u22e0");b["&npre;"]=new c("\u2aaf\u0338");b["&nprec;"]=new c("\u2280");b["&npreceq;"]=new c("\u2aaf\u0338");b["&nrarr;"]=new c("\u219b");b["&nrArr;"]=new c("\u21cf");b["&nrarrc;"]=new c("\u2933\u0338");b["&nrarrw;"]=new c("\u219d\u0338");b["&nrightarrow;"]=new c("\u219b");b["&nRightarrow;"]=new c("\u21cf");b["&nrtri;"]=new c("\u22eb");b["&nrtrie;"]=new c("\u22ed");b["&nsc;"]=new c("\u2281");b["&nsccue;"]=
new c("\u22e1");b["&nsce;"]=new c("\u2ab0\u0338");b["&nscr;"]=new c("\ud835\udcc3");b["&Nscr;"]=new c("\ud835\udca9");b["&nshortmid;"]=new c("\u2224");b["&nshortparallel;"]=new c("\u2226");b["&nsim;"]=new c("\u2241");b["&nsime;"]=new c("\u2244");b["&nsimeq;"]=new c("\u2244");b["&nsmid;"]=new c("\u2224");b["&nspar;"]=new c("\u2226");b["&nsqsube;"]=new c("\u22e2");b["&nsqsupe;"]=new c("\u22e3");b["&nsub;"]=new c("\u2284");b["&nsube;"]=new c("\u2288");b["&nsubE;"]=new c("\u2ac5\u0338");b["&nsubset;"]=
new c("\u2282\u20d2");b["&nsubseteq;"]=new c("\u2288");b["&nsubseteqq;"]=new c("\u2ac5\u0338");b["&nsucc;"]=new c("\u2281");b["&nsucceq;"]=new c("\u2ab0\u0338");b["&nsup;"]=new c("\u2285");b["&nsupe;"]=new c("\u2289");b["&nsupE;"]=new c("\u2ac6\u0338");b["&nsupset;"]=new c("\u2283\u20d2");b["&nsupseteq;"]=new c("\u2289");b["&nsupseteqq;"]=new c("\u2ac6\u0338");b["&ntgl;"]=new c("\u2279");b["&ntilde;"]=new c("\u00f1");b["&Ntilde;"]=new c("\u00d1");b["&ntlg;"]=new c("\u2278");b["&ntriangleleft;"]=new c("\u22ea");
b["&ntrianglelefteq;"]=new c("\u22ec");b["&ntriangleright;"]=new c("\u22eb");b["&ntrianglerighteq;"]=new c("\u22ed");b["&nu;"]=new c("\u03bd");b["&num;"]=new c("#");b["&numero;"]=new c("\u2116");b["&numsp;"]=new c("\u2007");b["&nvap;"]=new c("\u224d\u20d2");b["&nvdash;"]=new c("\u22ac");b["&nvDash;"]=new c("\u22ad");b["&nVdash;"]=new c("\u22ae");b["&nVDash;"]=new c("\u22af");b["&nvge;"]=new c("\u2265\u20d2");b["&nvgt;"]=new c(">\u20d2");b["&nvHarr;"]=new c("\u2904");b["&nvinfin;"]=new c("\u29de");
b["&nvlArr;"]=new c("\u2902");b["&nvle;"]=new c("\u2264\u20d2");b["&nvlt;"]=new c("<\u20d2");b["&nvltrie;"]=new c("\u22b4\u20d2");b["&nvrArr;"]=new c("\u2903");b["&nvrtrie;"]=new c("\u22b5\u20d2");b["&nvsim;"]=new c("\u223c\u20d2");b["&nwarhk;"]=new c("\u2923");b["&nwarr;"]=new c("\u2196");b["&nwArr;"]=new c("\u21d6");b["&nwarrow;"]=new c("\u2196");b["&nwnear;"]=new c("\u2927");b["&oacute;"]=new c("\u00f3");b["&Oacute;"]=new c("\u00d3");b["&oast;"]=new c("\u229b");b["&ocir;"]=new c("\u229a");b["&ocirc;"]=
new c("\u00f4");b["&Ocirc;"]=new c("\u00d4");b["&ocy;"]=new c("\u043e");b["&Ocy;"]=new c("\u041e");b["&odash;"]=new c("\u229d");b["&odblac;"]=new c("\u0151");b["&Odblac;"]=new c("\u0150");b["&odiv;"]=new c("\u2a38");b["&odot;"]=new c("\u2299");b["&odsold;"]=new c("\u29bc");b["&oelig;"]=new c("\u0153");b["&OElig;"]=new c("\u0152");b["&ofcir;"]=new c("\u29bf");b["&ofr;"]=new c("\ud835\udd2c");b["&Ofr;"]=new c("\ud835\udd12");b["&ogon;"]=new c("\u02db");b["&ograve;"]=new c("\u00f2");b["&Ograve;"]=new c("\u00d2");
b["&ogt;"]=new c("\u29c1");b["&ohbar;"]=new c("\u29b5");b["&ohm;"]=new c("\u2126");b["&oint;"]=new c("\u222e");b["&olarr;"]=new c("\u21ba");b["&olcir;"]=new c("\u29be");b["&olcross;"]=new c("\u29bb");b["&olt;"]=new c("\u29c0");b["&omacr;"]=new c("\u014d");b["&Omacr;"]=new c("\u014c");b["&omega;"]=new c("\u03c9");b["&Omega;"]=new c("\u03a9");b["&omid;"]=new c("\u29b6");b["&ominus;"]=new c("\u2296");b["&oopf;"]=new c("\ud835\udd60");b["&Oopf;"]=new c("\ud835\udd46");b["&opar;"]=new c("\u29b7");b["&OpenCurlyDoubleQuote;"]=
new c("\u201c");b["&OpenCurlyQuote;"]=new c("\u2018");b["&operp;"]=new c("\u29b9");b["&oplus;"]=new c("\u2295");b["&or;"]=new c("\u2228");b["&Or;"]=new c("\u2a54");b["&orarr;"]=new c("\u21bb");b["&ord;"]=new c("\u2a5d");b["&order;"]=new c("\u2134");b["&orderof;"]=new c("\u2134");b["&ordf;"]=new c("\u00aa");b["&ordm;"]=new c("\u00ba");b["&origof;"]=new c("\u22b6");b["&oror;"]=new c("\u2a56");b["&orslope;"]=new c("\u2a57");b["&orv;"]=new c("\u2a5b");b["&oS;"]=new c("\u24c8");b["&oscr;"]=new c("\u2134");
b["&Oscr;"]=new c("\ud835\udcaa");b["&oslash;"]=new c("\u00f8");b["&Oslash;"]=new c("\u00d8");b["&osol;"]=new c("\u2298");b["&otilde;"]=new c("\u00f5");b["&Otilde;"]=new c("\u00d5");b["&otimes;"]=new c("\u2297");b["&Otimes;"]=new c("\u2a37");b["&otimesas;"]=new c("\u2a36");b["&ouml;"]=new c("\u00f6");b["&Ouml;"]=new c("\u00d6");b["&ovbar;"]=new c("\u233d");b["&OverBar;"]=new c("\u00af");b["&OverBrace;"]=new c("\ufe37");b["&OverBracket;"]=new c("\u23b4");b["&OverParenthesis;"]=new c("\ufe35");b["&par;"]=
new c("\u2225");b["&para;"]=new c("\u00b6");b["&parallel;"]=new c("\u2225");b["&parsim;"]=new c("\u2af3");b["&parsl;"]=new c("\u2afd");b["&part;"]=new c("\u2202");b["&PartialD;"]=new c("\u2202");b["&pcy;"]=new c("\u043f");b["&Pcy;"]=new c("\u041f");b["&percnt;"]=new c("%");b["&period;"]=new c(".");b["&permil;"]=new c("\u2030");b["&perp;"]=new c("\u22a5");b["&pertenk;"]=new c("\u2031");b["&pfr;"]=new c("\ud835\udd2d");b["&Pfr;"]=new c("\ud835\udd13");b["&phi;"]=new c("\u03d5");b["&Phi;"]=new c("\u03a6");
b["&phiv;"]=new c("\u03c6");b["&phmmat;"]=new c("\u2133");b["&phone;"]=new c("\u260e");b["&pi;"]=new c("\u03c0");b["&Pi;"]=new c("\u03a0");b["&pitchfork;"]=new c("\u22d4");b["&piv;"]=new c("\u03d6");b["&planck;"]=new c("\u210f");b["&planckh;"]=new c("\u210e");b["&plankv;"]=new c("\u210f");b["&plus;"]=new c("+");b["&plusacir;"]=new c("\u2a23");b["&plusb;"]=new c("\u229e");b["&pluscir;"]=new c("\u2a22");b["&plusdo;"]=new c("\u2214");b["&plusdu;"]=new c("\u2a25");b["&pluse;"]=new c("\u2a72");b["&PlusMinus;"]=
new c("\u00b1");b["&plusmn;"]=new c("\u00b1");b["&plussim;"]=new c("\u2a26");b["&plustwo;"]=new c("\u2a27");b["&pm;"]=new c("\u00b1");b["&Poincareplane;"]=new c("\u210c");b["&pointint;"]=new c("\u2a15");b["&popf;"]=new c("\ud835\udd61");b["&Popf;"]=new c("\u2119");b["&pound;"]=new c("\u00a3");b["&pr;"]=new c("\u227a");b["&Pr;"]=new c("\u2abb");b["&prap;"]=new c("\u2ab7");b["&prcue;"]=new c("\u227c");b["&pre;"]=new c("\u2aaf");b["&prE;"]=new c("\u2ab3");b["&prec;"]=new c("\u227a");b["&precapprox;"]=
new c("\u2ab7");b["&preccurlyeq;"]=new c("\u227c");b["&Precedes;"]=new c("\u227a");b["&PrecedesEqual;"]=new c("\u2aaf");b["&PrecedesSlantEqual;"]=new c("\u227c");b["&PrecedesTilde;"]=new c("\u227e");b["&preceq;"]=new c("\u2aaf");b["&precnapprox;"]=new c("\u2ab9");b["&precneqq;"]=new c("\u2ab5");b["&precnsim;"]=new c("\u22e8");b["&precsim;"]=new c("\u227e");b["&prime;"]=new c("\u2032");b["&Prime;"]=new c("\u2033");b["&primes;"]=new c("\u2119");b["&prnap;"]=new c("\u2ab9");b["&prnE;"]=new c("\u2ab5");
b["&prnsim;"]=new c("\u22e8");b["&prod;"]=new c("\u220f");b["&Product;"]=new c("\u220f");b["&profalar;"]=new c("\u232e");b["&profline;"]=new c("\u2312");b["&profsurf;"]=new c("\u2313");b["&prop;"]=new c("\u221d");b["&Proportion;"]=new c("\u2237");b["&Proportional;"]=new c("\u221d");b["&propto;"]=new c("\u221d");b["&prsim;"]=new c("\u227e");b["&prurel;"]=new c("\u22b0");b["&pscr;"]=new c("\ud835\udcc5");b["&Pscr;"]=new c("\ud835\udcab");b["&psi;"]=new c("\u03c8");b["&Psi;"]=new c("\u03a8");b["&puncsp;"]=
new c("\u2008");b["&qfr;"]=new c("\ud835\udd2e");b["&Qfr;"]=new c("\ud835\udd14");b["&qint;"]=new c("\u2a0c");b["&qopf;"]=new c("\ud835\udd62");b["&Qopf;"]=new c("\u211a");b["&qprime;"]=new c("\u2057");b["&qscr;"]=new c("\ud835\udcc6");b["&Qscr;"]=new c("\ud835\udcac");b["&quaternions;"]=new c("\u210d");b["&quatint;"]=new c("\u2a16");b["&quest;"]=new c("?");b["&questeq;"]=new c("\u225f");b["&quot;"]=new c('"');b["&rAarr;"]=new c("\u21db");b["&race;"]=new c("\u29da");b["&racute;"]=new c("\u0155");
b["&Racute;"]=new c("\u0154");b["&radic;"]=new c("\u221a");b["&raemptyv;"]=new c("\u29b3");b["&rang;"]=new c("\u232a");b["&Rang;"]=new c("\u300b");b["&rangd;"]=new c("\u2992");b["&range;"]=new c("\u29a5");b["&rangle;"]=new c("\u232a");b["&raquo;"]=new c("\u00bb");b["&rarr;"]=new c("\u2192");b["&rArr;"]=new c("\u21d2");b["&Rarr;"]=new c("\u21a0");b["&rarrap;"]=new c("\u2975");b["&rarrb;"]=new c("\u21e5");b["&rarrbfs;"]=new c("\u2920");b["&rarrc;"]=new c("\u2933");b["&rarrfs;"]=new c("\u291e");b["&rarrhk;"]=
new c("\u21aa");b["&rarrlp;"]=new c("\u21ac");b["&rarrpl;"]=new c("\u2945");b["&rarrsim;"]=new c("\u2974");b["&rarrtl;"]=new c("\u21a3");b["&Rarrtl;"]=new c("\u2916");b["&rarrw;"]=new c("\u219d");b["&ratail;"]=new c("\u291a");b["&rAtail;"]=new c("\u291c");b["&ratio;"]=new c("\u2236");b["&rationals;"]=new c("\u211a");b["&rbarr;"]=new c("\u290d");b["&rBarr;"]=new c("\u290f");b["&RBarr;"]=new c("\u2910");b["&rbbrk;"]=new c("\u3015");b["&rbrace;"]=new c("}");b["&rbrack;"]=new c("]");b["&rbrke;"]=new c("\u298c");
b["&rbrksld;"]=new c("\u298e");b["&rbrkslu;"]=new c("\u2990");b["&rcaron;"]=new c("\u0159");b["&Rcaron;"]=new c("\u0158");b["&rcedil;"]=new c("\u0157");b["&Rcedil;"]=new c("\u0156");b["&rceil;"]=new c("\u2309");b["&rcub;"]=new c("}");b["&rcy;"]=new c("\u0440");b["&Rcy;"]=new c("\u0420");b["&rdca;"]=new c("\u2937");b["&rdldhar;"]=new c("\u2969");b["&rdquo;"]=new c("\u201d");b["&rdquor;"]=new c("\u201d");b["&rdsh;"]=new c("\u21b3");b["&Re;"]=new c("\u211c");b["&real;"]=new c("\u211c");b["&realine;"]=
new c("\u211b");b["&realpart;"]=new c("\u211c");b["&reals;"]=new c("\u211d");b["&rect;"]=new c("\u25ad");b["&reg;"]=new c("\u00ae");b["&ReverseElement;"]=new c("\u220b");b["&ReverseEquilibrium;"]=new c("\u21cb");b["&ReverseUpEquilibrium;"]=new c("\u296f");b["&rfisht;"]=new c("\u297d");b["&rfloor;"]=new c("\u230b");b["&rfr;"]=new c("\ud835\udd2f");b["&Rfr;"]=new c("\u211c");b["&rHar;"]=new c("\u2964");b["&rhard;"]=new c("\u21c1");b["&rharu;"]=new c("\u21c0");b["&rharul;"]=new c("\u296c");b["&rho;"]=
new c("\u03c1");b["&rhov;"]=new c("\u03f1");b["&RightAngleBracket;"]=new c("\u232a");b["&rightarrow;"]=new c("\u2192");b["&Rightarrow;"]=new c("\u21d2");b["&RightArrow;"]=new c("\u2192");b["&RightArrowBar;"]=new c("\u21e5");b["&RightArrowLeftArrow;"]=new c("\u21c4");b["&rightarrowtail;"]=new c("\u21a3");b["&RightCeiling;"]=new c("\u2309");b["&RightDoubleBracket;"]=new c("\u301b");b["&RightDownTeeVector;"]=new c("\u295d");b["&RightDownVector;"]=new c("\u21c2");b["&RightDownVectorBar;"]=new c("\u2955");
b["&RightFloor;"]=new c("\u230b");b["&rightharpoondown;"]=new c("\u21c1");b["&rightharpoonup;"]=new c("\u21c0");b["&rightleftarrows;"]=new c("\u21c4");b["&rightleftharpoons;"]=new c("\u21cc");b["&rightrightarrows;"]=new c("\u21c9");b["&rightsquigarrow;"]=new c("\u219d");b["&RightTee;"]=new c("\u22a2");b["&RightTeeArrow;"]=new c("\u21a6");b["&RightTeeVector;"]=new c("\u295b");b["&rightthreetimes;"]=new c("\u22cc");b["&RightTriangle;"]=new c("\u22b3");b["&RightTriangleBar;"]=new c("\u29d0");b["&RightTriangleEqual;"]=
new c("\u22b5");b["&RightUpDownVector;"]=new c("\u294f");b["&RightUpTeeVector;"]=new c("\u295c");b["&RightUpVector;"]=new c("\u21be");b["&RightUpVectorBar;"]=new c("\u2954");b["&RightVector;"]=new c("\u21c0");b["&RightVectorBar;"]=new c("\u2953");b["&ring;"]=new c("\u02da");b["&risingdotseq;"]=new c("\u2253");b["&rlarr;"]=new c("\u21c4");b["&rlhar;"]=new c("\u21cc");b["&rmoust;"]=new c("\u23b1");b["&rmoustache;"]=new c("\u23b1");b["&rnmid;"]=new c("\u2aee");b["&roang;"]=new c("\u3019");b["&roarr;"]=
new c("\u21fe");b["&robrk;"]=new c("\u301b");b["&ropar;"]=new c("\u2986");b["&ropf;"]=new c("\ud835\udd63");b["&Ropf;"]=new c("\u211d");b["&roplus;"]=new c("\u2a2e");b["&rotimes;"]=new c("\u2a35");b["&RoundImplies;"]=new c("\u2970");b["&rpar;"]=new c(")");b["&rpargt;"]=new c("\u2994");b["&rppolint;"]=new c("\u2a12");b["&rrarr;"]=new c("\u21c9");b["&Rrightarrow;"]=new c("\u21db");b["&rscr;"]=new c("\ud835\udcc7");b["&Rscr;"]=new c("\u211b");b["&rsh;"]=new c("\u21b1");b["&Rsh;"]=new c("\u21b1");b["&rsqb;"]=
new c("]");b["&rsquo;"]=new c("\u2019");b["&rsquor;"]=new c("\u2019");b["&rthree;"]=new c("\u22cc");b["&rtimes;"]=new c("\u22ca");b["&rtri;"]=new c("\u25b9");b["&rtrie;"]=new c("\u22b5");b["&rtrif;"]=new c("\u25b8");b["&rtriltri;"]=new c("\u29ce");b["&RuleDelayed;"]=new c("\u29f4");b["&ruluhar;"]=new c("\u2968");b["&rx;"]=new c("\u211e");b["&sacute;"]=new c("\u015b");b["&Sacute;"]=new c("\u015a");b["&sc;"]=new c("\u227b");b["&Sc;"]=new c("\u2abc");b["&scap;"]=new c("\u2ab8");b["&scaron;"]=new c("\u0161");
b["&Scaron;"]=new c("\u0160");b["&sccue;"]=new c("\u227d");b["&sce;"]=new c("\u2ab0");b["&scE;"]=new c("\u2ab4");b["&scedil;"]=new c("\u015f");b["&Scedil;"]=new c("\u015e");b["&scirc;"]=new c("\u015d");b["&Scirc;"]=new c("\u015c");b["&scnap;"]=new c("\u2aba");b["&scnE;"]=new c("\u2ab6");b["&scnsim;"]=new c("\u22e9");b["&scpolint;"]=new c("\u2a13");b["&scsim;"]=new c("\u227f");b["&scy;"]=new c("\u0441");b["&Scy;"]=new c("\u0421");b["&sdot;"]=new c("\u22c5");b["&sdotb;"]=new c("\u22a1");b["&sdote;"]=
new c("\u2a66");b["&searhk;"]=new c("\u2925");b["&searr;"]=new c("\u2198");b["&seArr;"]=new c("\u21d8");b["&searrow;"]=new c("\u2198");b["&sect;"]=new c("\u00a7");b["&semi;"]=new c(";");b["&seswar;"]=new c("\u2929");b["&setminus;"]=new c("\u2216");b["&setmn;"]=new c("\u2216");b["&sext;"]=new c("\u2736");b["&sfr;"]=new c("\ud835\udd30");b["&Sfr;"]=new c("\ud835\udd16");b["&sfrown;"]=new c("\u2322");b["&sharp;"]=new c("\u266f");b["&shchcy;"]=new c("\u0449");b["&SHCHcy;"]=new c("\u0429");b["&shcy;"]=
new c("\u0448");b["&SHcy;"]=new c("\u0428");b["&ShortDownArrow;"]=new c("\u2193");b["&ShortLeftArrow;"]=new c("\u2190");b["&shortmid;"]=new c("\u2223");b["&shortparallel;"]=new c("\u2225");b["&ShortRightArrow;"]=new c("\u2192");b["&ShortUpArrow;"]=new c("\u2191");b["&shy;"]=new c("\u00ad");b["&sigma;"]=new c("\u03c3");b["&Sigma;"]=new c("\u03a3");b["&sigmav;"]=new c("\u03c2");b["&sim;"]=new c("\u223c");b["&simdot;"]=new c("\u2a6a");b["&sime;"]=new c("\u2243");b["&simeq;"]=new c("\u2243");b["&simg;"]=
new c("\u2a9e");b["&simgE;"]=new c("\u2aa0");b["&siml;"]=new c("\u2a9d");b["&simlE;"]=new c("\u2a9f");b["&simne;"]=new c("\u2246");b["&simplus;"]=new c("\u2a24");b["&simrarr;"]=new c("\u2972");b["&slarr;"]=new c("\u2190");b["&SmallCircle;"]=new c("\u2218");b["&smallsetminus;"]=new c("\u2216");b["&smashp;"]=new c("\u2a33");b["&smeparsl;"]=new c("\u29e4");b["&smid;"]=new c("\u2223");b["&smile;"]=new c("\u2323");b["&smt;"]=new c("\u2aaa");b["&smte;"]=new c("\u2aac");b["&smtes;"]=new c("\u2aac\ufe00");
b["&softcy;"]=new c("\u044c");b["&SOFTcy;"]=new c("\u042c");b["&sol;"]=new c("/");b["&solb;"]=new c("\u29c4");b["&solbar;"]=new c("\u233f");b["&sopf;"]=new c("\ud835\udd64");b["&Sopf;"]=new c("\ud835\udd4a");b["&spades;"]=new c("\u2660");b["&spadesuit;"]=new c("\u2660");b["&spar;"]=new c("\u2225");b["&sqcap;"]=new c("\u2293");b["&sqcaps;"]=new c("\u2293\ufe00");b["&sqcup;"]=new c("\u2294");b["&sqcups;"]=new c("\u2294\ufe00");b["&Sqrt;"]=new c("\u221a");b["&sqsub;"]=new c("\u228f");b["&sqsube;"]=new c("\u2291");
b["&sqsubset;"]=new c("\u228f");b["&sqsubseteq;"]=new c("\u2291");b["&sqsup;"]=new c("\u2290");b["&sqsupe;"]=new c("\u2292");b["&sqsupset;"]=new c("\u2290");b["&sqsupseteq;"]=new c("\u2292");b["&squ;"]=new c("\u25a1");b["&square;"]=new c("\u25a1");b["&Square;"]=new c("\u25a1");b["&SquareIntersection;"]=new c("\u2293");b["&SquareSubset;"]=new c("\u228f");b["&SquareSubsetEqual;"]=new c("\u2291");b["&SquareSuperset;"]=new c("\u2290");b["&SquareSupersetEqual;"]=new c("\u2292");b["&SquareUnion;"]=new c("\u2294");
b["&squarf;"]=new c("\u25aa");b["&squf;"]=new c("\u25aa");b["&srarr;"]=new c("\u2192");b["&sscr;"]=new c("\ud835\udcc8");b["&Sscr;"]=new c("\ud835\udcae");b["&ssetmn;"]=new c("\u2216");b["&ssmile;"]=new c("\u2323");b["&sstarf;"]=new c("\u22c6");b["&star;"]=new c("\u2606");b["&Star;"]=new c("\u22c6");b["&starf;"]=new c("\u2605");b["&straightepsilon;"]=new c("\u03f5");b["&straightphi;"]=new c("\u03d5");b["&strns;"]=new c("\u00af");b["&sub;"]=new c("\u2282");b["&Sub;"]=new c("\u22d0");b["&subdot;"]=
new c("\u2abd");b["&sube;"]=new c("\u2286");b["&subE;"]=new c("\u2ac5");b["&subedot;"]=new c("\u2ac3");b["&submult;"]=new c("\u2ac1");b["&subne;"]=new c("\u228a");b["&subnE;"]=new c("\u2acb");b["&subplus;"]=new c("\u2abf");b["&subrarr;"]=new c("\u2979");b["&subset;"]=new c("\u2282");b["&Subset;"]=new c("\u22d0");b["&subseteq;"]=new c("\u2286");b["&subseteqq;"]=new c("\u2ac5");b["&SubsetEqual;"]=new c("\u2286");b["&subsetneq;"]=new c("\u228a");b["&subsetneqq;"]=new c("\u2acb");b["&subsim;"]=new c("\u2ac7");
b["&subsub;"]=new c("\u2ad5");b["&subsup;"]=new c("\u2ad3");b["&succ;"]=new c("\u227b");b["&succapprox;"]=new c("\u2ab8");b["&succcurlyeq;"]=new c("\u227d");b["&Succeeds;"]=new c("\u227b");b["&SucceedsEqual;"]=new c("\u2ab0");b["&SucceedsSlantEqual;"]=new c("\u227d");b["&SucceedsTilde;"]=new c("\u227f");b["&succeq;"]=new c("\u2ab0");b["&succnapprox;"]=new c("\u2aba");b["&succneqq;"]=new c("\u2ab6");b["&succnsim;"]=new c("\u22e9");b["&succsim;"]=new c("\u227f");b["&SuchThat;"]=new c("\u220b");b["&sum;"]=
new c("\u2211");b["&Sum;"]=new c("\u2211");b["&sung;"]=new c("\u266a");b["&sup;"]=new c("\u2283");b["&Sup;"]=new c("\u22d1");b["&sup1;"]=new c("\u00b9");b["&sup2;"]=new c("\u00b2");b["&sup3;"]=new c("\u00b3");b["&supdot;"]=new c("\u2abe");b["&supdsub;"]=new c("\u2ad8");b["&supe;"]=new c("\u2287");b["&supE;"]=new c("\u2ac6");b["&supedot;"]=new c("\u2ac4");b["&Superset;"]=new c("\u2283");b["&SupersetEqual;"]=new c("\u2287");b["&suphsol;"]=new c("\u2283/");b["&suphsub;"]=new c("\u2ad7");b["&suplarr;"]=
new c("\u297b");b["&supmult;"]=new c("\u2ac2");b["&supne;"]=new c("\u228b");b["&supnE;"]=new c("\u2acc");b["&supplus;"]=new c("\u2ac0");b["&supset;"]=new c("\u2283");b["&Supset;"]=new c("\u22d1");b["&supseteq;"]=new c("\u2287");b["&supseteqq;"]=new c("\u2ac6");b["&supsetneq;"]=new c("\u228b");b["&supsetneqq;"]=new c("\u2acc");b["&supsim;"]=new c("\u2ac8");b["&supsub;"]=new c("\u2ad4");b["&supsup;"]=new c("\u2ad6");b["&swarhk;"]=new c("\u2926");b["&swarr;"]=new c("\u2199");b["&swArr;"]=new c("\u21d9");
b["&swarrow;"]=new c("\u2199");b["&swnwar;"]=new c("\u292a");b["&szlig;"]=new c("\u00df");b["&Tab;"]=new c("\t");b["&target;"]=new c("\u2316");b["&tau;"]=new c("\u03c4");b["&tbrk;"]=new c("\u23b4");b["&tcaron;"]=new c("\u0165");b["&Tcaron;"]=new c("\u0164");b["&tcedil;"]=new c("\u0163");b["&Tcedil;"]=new c("\u0162");b["&tcy;"]=new c("\u0442");b["&Tcy;"]=new c("\u0422");b["&tdot;"]=new c("\u20db");b["&telrec;"]=new c("\u2315");b["&tfr;"]=new c("\ud835\udd31");b["&Tfr;"]=new c("\ud835\udd17");b["&there4;"]=
new c("\u2234");b["&therefore;"]=new c("\u2234");b["&Therefore;"]=new c("\u2234");b["&theta;"]=new c("\u03b8");b["&Theta;"]=new c("\u0398");b["&thetav;"]=new c("\u03d1");b["&thickapprox;"]=new c("\u2248");b["&thicksim;"]=new c("\u223c");b["&ThickSpace;"]=new c("\u2009\u200a\u200a");b["&thinsp;"]=new c("\u2009");b["&ThinSpace;"]=new c("\u2009");b["&thkap;"]=new c("\u2248");b["&thksim;"]=new c("\u223c");b["&thorn;"]=new c("\u00fe");b["&THORN;"]=new c("\u00de");b["&tilde;"]=new c("\u02dc");b["&Tilde;"]=
new c("\u223c");b["&TildeEqual;"]=new c("\u2243");b["&TildeFullEqual;"]=new c("\u2245");b["&TildeTilde;"]=new c("\u2248");b["&times;"]=new c("\u00d7");b["&timesb;"]=new c("\u22a0");b["&timesbar;"]=new c("\u2a31");b["&timesd;"]=new c("\u2a30");b["&tint;"]=new c("\u222d");b["&toea;"]=new c("\u2928");b["&top;"]=new c("\u22a4");b["&topbot;"]=new c("\u2336");b["&topcir;"]=new c("\u2af1");b["&topf;"]=new c("\ud835\udd65");b["&Topf;"]=new c("\ud835\udd4b");b["&topfork;"]=new c("\u2ada");b["&tosa;"]=new c("\u2929");
b["&tprime;"]=new c("\u2034");b["&trade;"]=new c("\u2122");b["&triangle;"]=new c("\u25b5");b["&triangledown;"]=new c("\u25bf");b["&triangleleft;"]=new c("\u25c3");b["&trianglelefteq;"]=new c("\u22b4");b["&triangleq;"]=new c("\u225c");b["&triangleright;"]=new c("\u25b9");b["&trianglerighteq;"]=new c("\u22b5");b["&tridot;"]=new c("\u25ec");b["&trie;"]=new c("\u225c");b["&triminus;"]=new c("\u2a3a");b["&TripleDot;"]=new c("\u20db");b["&triplus;"]=new c("\u2a39");b["&trisb;"]=new c("\u29cd");b["&tritime;"]=
new c("\u2a3b");b["&trpezium;"]=new c("\ufffd");b["&tscr;"]=new c("\ud835\udcc9");b["&Tscr;"]=new c("\ud835\udcaf");b["&tscy;"]=new c("\u0446");b["&TScy;"]=new c("\u0426");b["&tshcy;"]=new c("\u045b");b["&TSHcy;"]=new c("\u040b");b["&tstrok;"]=new c("\u0167");b["&Tstrok;"]=new c("\u0166");b["&twixt;"]=new c("\u226c");b["&twoheadleftarrow;"]=new c("\u219e");b["&twoheadrightarrow;"]=new c("\u21a0");b["&uacute;"]=new c("\u00fa");b["&Uacute;"]=new c("\u00da");b["&uarr;"]=new c("\u2191");b["&uArr;"]=new c("\u21d1");
b["&Uarr;"]=new c("\u219f");b["&Uarrocir;"]=new c("\u2949");b["&ubrcy;"]=new c("\u045e");b["&Ubrcy;"]=new c("\u040e");b["&ubreve;"]=new c("\u016d");b["&Ubreve;"]=new c("\u016c");b["&ucirc;"]=new c("\u00fb");b["&Ucirc;"]=new c("\u00db");b["&ucy;"]=new c("\u0443");b["&Ucy;"]=new c("\u0423");b["&udarr;"]=new c("\u21c5");b["&udblac;"]=new c("\u0171");b["&Udblac;"]=new c("\u0170");b["&udhar;"]=new c("\u296e");b["&ufisht;"]=new c("\u297e");b["&ufr;"]=new c("\ud835\udd32");b["&Ufr;"]=new c("\ud835\udd18");
b["&ugrave;"]=new c("\u00f9");b["&Ugrave;"]=new c("\u00d9");b["&uHar;"]=new c("\u2963");b["&uharl;"]=new c("\u21bf");b["&uharr;"]=new c("\u21be");b["&uhblk;"]=new c("\u2580");b["&ulcorn;"]=new c("\u231c");b["&ulcorner;"]=new c("\u231c");b["&ulcrop;"]=new c("\u230f");b["&ultri;"]=new c("\u25f8");b["&umacr;"]=new c("\u016b");b["&Umacr;"]=new c("\u016a");b["&uml;"]=new c("\u00a8");b["&UnderBar;"]=new c("\u0332");b["&UnderBrace;"]=new c("\ufe38");b["&UnderBracket;"]=new c("\u23b5");b["&UnderParenthesis;"]=
new c("\ufe36");b["&Union;"]=new c("\u22c3");b["&UnionPlus;"]=new c("\u228e");b["&uogon;"]=new c("\u0173");b["&Uogon;"]=new c("\u0172");b["&uopf;"]=new c("\ud835\udd66");b["&Uopf;"]=new c("\ud835\udd4c");b["&uparrow;"]=new c("\u2191");b["&Uparrow;"]=new c("\u21d1");b["&UpArrow;"]=new c("\u2191");b["&UpArrowBar;"]=new c("\u2912");b["&UpArrowDownArrow;"]=new c("\u21c5");b["&updownarrow;"]=new c("\u2195");b["&Updownarrow;"]=new c("\u21d5");b["&UpDownArrow;"]=new c("\u2195");b["&UpEquilibrium;"]=new c("\u296e");
b["&upharpoonleft;"]=new c("\u21bf");b["&upharpoonright;"]=new c("\u21be");b["&uplus;"]=new c("\u228e");b["&UpperLeftArrow;"]=new c("\u2196");b["&UpperRightArrow;"]=new c("\u2197");b["&upsi;"]=new c("\u03c5");b["&Upsi;"]=new c("\u03d2");b["&upsilon;"]=new c("\u03c5");b["&Upsilon;"]=new c("\u03a5");b["&UpTee;"]=new c("\u22a5");b["&UpTeeArrow;"]=new c("\u21a5");b["&upuparrows;"]=new c("\u21c8");b["&urcorn;"]=new c("\u231d");b["&urcorner;"]=new c("\u231d");b["&urcrop;"]=new c("\u230e");b["&uring;"]=
new c("\u016f");b["&Uring;"]=new c("\u016e");b["&urtri;"]=new c("\u25f9");b["&uscr;"]=new c("\ud835\udcca");b["&Uscr;"]=new c("\ud835\udcb0");b["&utdot;"]=new c("\u22f0");b["&utilde;"]=new c("\u0169");b["&Utilde;"]=new c("\u0168");b["&utri;"]=new c("\u25b5");b["&utrif;"]=new c("\u25b4");b["&uuarr;"]=new c("\u21c8");b["&uuml;"]=new c("\u00fc");b["&Uuml;"]=new c("\u00dc");b["&uwangle;"]=new c("\u29a7");b["&vangrt;"]=new c("\u299c");b["&varepsilon;"]=new c("\u03b5");b["&varkappa;"]=new c("\u03f0");b["&varnothing;"]=
new c("\u2205");b["&varphi;"]=new c("\u03c6");b["&varpi;"]=new c("\u03d6");b["&varpropto;"]=new c("\u221d");b["&varr;"]=new c("\u2195");b["&vArr;"]=new c("\u21d5");b["&varrho;"]=new c("\u03f1");b["&varsigma;"]=new c("\u03c2");b["&varsubsetneq;"]=new c("\u228a\ufe00");b["&varsubsetneqq;"]=new c("\u2acb\ufe00");b["&varsupsetneq;"]=new c("\u228b\ufe00");b["&varsupsetneqq;"]=new c("\u2acc\ufe00");b["&vartheta;"]=new c("\u03d1");b["&vartriangleleft;"]=new c("\u22b2");b["&vartriangleright;"]=new c("\u22b3");
b["&vBar;"]=new c("\u2ae8");b["&Vbar;"]=new c("\u2aeb");b["&vBarv;"]=new c("\u2ae9");b["&vcy;"]=new c("\u0432");b["&Vcy;"]=new c("\u0412");b["&vdash;"]=new c("\u22a2");b["&vDash;"]=new c("\u22a8");b["&Vdash;"]=new c("\u22a9");b["&VDash;"]=new c("\u22ab");b["&Vdashl;"]=new c("\u2ae6");b["&vee;"]=new c("\u2228");b["&Vee;"]=new c("\u22c1");b["&veebar;"]=new c("\u22bb");b["&veeeq;"]=new c("\u225a");b["&vellip;"]=new c("\u22ee");b["&verbar;"]=new c("|");b["&Verbar;"]=new c("\u2016");b["&vert;"]=new c("|");
b["&Vert;"]=new c("\u2016");b["&VerticalBar;"]=new c("\u2223");b["&VerticalLine;"]=new c("|");b["&VerticalSeparator;"]=new c("\u2758");b["&VerticalTilde;"]=new c("\u2240");b["&VeryThinSpace;"]=new c("\u200a");b["&vfr;"]=new c("\ud835\udd33");b["&Vfr;"]=new c("\ud835\udd19");b["&vltri;"]=new c("\u22b2");b["&vnsub;"]=new c("\u2282\u20d2");b["&vnsup;"]=new c("\u2283\u20d2");b["&vopf;"]=new c("\ud835\udd67");b["&Vopf;"]=new c("\ud835\udd4d");b["&vprop;"]=new c("\u221d");b["&vrtri;"]=new c("\u22b3");b["&vscr;"]=
new c("\ud835\udccb");b["&Vscr;"]=new c("\ud835\udcb1");b["&vsubne;"]=new c("\u228a\ufe00");b["&vsubnE;"]=new c("\u2acb\ufe00");b["&vsupne;"]=new c("\u228b\ufe00");b["&vsupnE;"]=new c("\u2acc\ufe00");b["&Vvdash;"]=new c("\u22aa");b["&vzigzag;"]=new c("\u299a");b["&wcirc;"]=new c("\u0175");b["&Wcirc;"]=new c("\u0174");b["&wedbar;"]=new c("\u2a5f");b["&wedge;"]=new c("\u2227");b["&Wedge;"]=new c("\u22c0");b["&wedgeq;"]=new c("\u2259");b["&weierp;"]=new c("\u2118");b["&wfr;"]=new c("\ud835\udd34");b["&Wfr;"]=
new c("\ud835\udd1a");b["&wopf;"]=new c("\ud835\udd68");b["&Wopf;"]=new c("\ud835\udd4e");b["&wp;"]=new c("\u2118");b["&wr;"]=new c("\u2240");b["&wreath;"]=new c("\u2240");b["&wscr;"]=new c("\ud835\udccc");b["&Wscr;"]=new c("\ud835\udcb2");b["&xcap;"]=new c("\u22c2");b["&xcirc;"]=new c("\u25ef");b["&xcup;"]=new c("\u22c3");b["&xdtri;"]=new c("\u25bd");b["&xfr;"]=new c("\ud835\udd35");b["&Xfr;"]=new c("\ud835\udd1b");b["&xharr;"]=new c("\u27f7");b["&xhArr;"]=new c("\u27fa");b["&xi;"]=new c("\u03be");
b["&Xi;"]=new c("\u039e");b["&xlarr;"]=new c("\u27f5");b["&xlArr;"]=new c("\u27f8");b["&xmap;"]=new c("\u27fc");b["&xnis;"]=new c("\u22fb");b["&xodot;"]=new c("\u2a00");b["&xopf;"]=new c("\ud835\udd69");b["&Xopf;"]=new c("\ud835\udd4f");b["&xoplus;"]=new c("\u2a01");b["&xotime;"]=new c("\u2a02");b["&xrarr;"]=new c("\u27f6");b["&xrArr;"]=new c("\u27f9");b["&xscr;"]=new c("\ud835\udccd");b["&Xscr;"]=new c("\ud835\udcb3");b["&xsqcup;"]=new c("\u2a06");b["&xuplus;"]=new c("\u2a04");b["&xutri;"]=new c("\u25b3");
b["&xvee;"]=new c("\u22c1");b["&xwedge;"]=new c("\u22c0");b["&yacute;"]=new c("\u00fd");b["&Yacute;"]=new c("\u00dd");b["&yacy;"]=new c("\u044f");b["&YAcy;"]=new c("\u042f");b["&ycirc;"]=new c("\u0177");b["&Ycirc;"]=new c("\u0176");b["&ycy;"]=new c("\u044b");b["&Ycy;"]=new c("\u042b");b["&yen;"]=new c("\u00a5");b["&yfr;"]=new c("\ud835\udd36");b["&Yfr;"]=new c("\ud835\udd1c");b["&yicy;"]=new c("\u0457");b["&YIcy;"]=new c("\u0407");b["&yopf;"]=new c("\ud835\udd6a");b["&Yopf;"]=new c("\ud835\udd50");
b["&yscr;"]=new c("\ud835\udcce");b["&Yscr;"]=new c("\ud835\udcb4");b["&yucy;"]=new c("\u044e");b["&YUcy;"]=new c("\u042e");b["&yuml;"]=new c("\u00ff");b["&Yuml;"]=new c("\u0178");b["&zacute;"]=new c("\u017a");b["&Zacute;"]=new c("\u0179");b["&zcaron;"]=new c("\u017e");b["&Zcaron;"]=new c("\u017d");b["&zcy;"]=new c("\u0437");b["&Zcy;"]=new c("\u0417");b["&zdot;"]=new c("\u017c");b["&Zdot;"]=new c("\u017b");b["&zeetrf;"]=new c("\u2128");b["&ZeroWidthSpace;"]=new c("\u200b");b["&zeta;"]=new c("\u03b6");
b["&zfr;"]=new c("\ud835\udd37");b["&Zfr;"]=new c("\u2128");b["&zhcy;"]=new c("\u0436");b["&ZHcy;"]=new c("\u0416");b["&zigrarr;"]=new c("\u21dd");b["&zopf;"]=new c("\ud835\udd6b");b["&Zopf;"]=new c("\u2124");b["&zscr;"]=new c("\ud835\udccf");b["&Zscr;"]=new c("\ud835\udcb5")};D2L_MathML.CharacterEntity=function(b){this.m_character=b;this.GetCharacter=function(){return this.m_character}};typeof window.addEventListener!="undefined"&&window.addEventListener("load",D2L_MathML.RenderMathML,false);
typeof window.attachEvent!="undefined"&&window.attachEvent("onload",D2L_MathML.RenderMathML);window.D2L!==undefined&&D2L.LP.Web.Packaging!==undefined&&D2L.LP.Web.Packaging.Register("D2L.LP.Web.MathML");