
D2L.Control.Grid=D2L.Control.extend({Construct:function(){arguments.callee.$.Construct.call(this);this.nameOrMappedId="";this.type=D2L.Control.Grid.Type.Data;this.activatedKey="";this.pageNum=1;this.pageSize=20;this.sortField="";this.sortDir=1;this.sortFieldForState="";this.sortDirForState=1;this.isUsingDefaultSort=false;this.search=null;this.m_selectionAllowMultiple=true;this.m_slPgNm2=this.m_slPgNm1=this.m_slPgSz2=this.m_slPgSz1=this.m_treeType=null;this.m_treeRowsExpanded=true;this.m_treeRowExceptionKeys=
[];this.m_isSelectedExceptionKeys=[];this.m_rowIndex=1;this.OnSelectRow=new D2L.EventHandler;this.OnDeleteRow=new D2L.EventHandler;this.OnRestoreRow=new D2L.EventHandler;this.OnPageNumberChange=new D2L.EventHandler;this.OnPageSizeChange=new D2L.EventHandler;WindowEventManager.Transform.Register(this,"RefreshItemRowTrees");Nav.OnBeforeNavigate.Register(this,"OnNav")},IntegrateControlMin:function(b){arguments.callee.$.IntegrateControlMin.call(this,b);this.type=b.GetMember();this.isUsingDefaultSort=
b.GetBoolean();this.pageNum=b.GetMember();this.pageSize=b.GetMember();this.m_treeType=b.GetMember();this.m_selectionAllowMultiple=b.GetBoolean();this.sortField=b.GetMember();this.sortDir=b.GetMember();this.m_treeRowsExpanded=b.GetBoolean();this.m_treeRowExceptionKeys=b.GetDictionaryMin();this.m_isSelectedExceptionKeys=b.GetDictionaryMin();this.data=b.GetMember();this.m_rowIndex=b.GetMember();var c=b.GetMember();this.nameOrMappedId=b.GetMember();this.m_slPgSz1=UI.GetControl(this.GetMappedId()+"_sl_pgS1");
this.m_slPgSz2=UI.GetControl(this.GetMappedId()+"_sl_pgS2");this.m_slPgNm1=UI.GetControl(this.GetMappedId()+"_sl_pg1");this.m_slPgNm2=UI.GetControl(this.GetMappedId()+"_sl_pg2");this.Init();c.length>0&&this.Activate(c)},GetTreeRowsExpanded:function(){return this.m_treeRowsExpanded},GetTreeExceptionKeys:function(){return this.m_treeRowExceptionKeys},GetTreeExceptionKeysForState:function(){var b=[],c=this;this.ForEachRow(function(e){if(e.type=="i"&&e.isTreeNode){var f=e.GetKey(),g=c.GetTreeRowsExpanded();
if(c.GetTreeExceptionKeys()[f]){if(e.isExpanded==g)b[b.length]=f}else if(e.isExpanded!=g)b[b.length]=f}});return b},GetCollapsedKeys:function(){var b=[];this.ForEachRow(function(c){if(c.type=="i"&&c.isTreeNode){var e=c.GetKey();if(c.isExpanded==false)b[b.length]=e}});return b},GetExpandedKeys:function(){var b=[];this.ForEachRow(function(c){if(c.type=="i"&&c.isTreeNode){var e=c.GetKey();if(c.isExpanded==true)b[b.length]=e}});return b},GetIsSelectedExceptionKeys:function(){return this.m_isSelectedExceptionKeys},
GetIsSelectedExceptionKeysForState:function(){var b=[],c=this;this.ForEachRow(function(e){if(e.type=="i"){var f=e.IsSelected();e=e.GetKey();if(c.GetIsSelectedExceptionKeys()[e])f||(b[b.length]=e);else if(f)b[b.length]=e}});return b},GetSelectedGroupKeys:function(){return this.GetSelectedKeysForType("g")},GetSelectedKeys:function(){return this.GetSelectedKeysForType("i")},RefreshItemRowTrees:function(){var b;if(this.rowData&&this.rowData.allRows)for(b in this.rowData.allRows);},GetSelectedValues:function(){var b=
[],c,e;if(this.rowData&&this.rowData.allRows)for(c in this.rowData.allRows){e=this.rowData.allRows[c];e.type=="i"&&e.IsSelected()&&b.push(e.val)}return b},GetKeys:function(){var b=-1,c=[],e;if(this.rowData&&this.rowData.allRows)for(e in this.rowData.allRows){b=this.rowData.allRows[e];if(b.type=="i"){b=e.indexOf("_");if(b>=0&&b<e.length)e=e.substr(b+1);c.push(e)}}return c},GetState:function(b,c,e){if(c=="rowshowchanges"){c=this.GetRow(e);if(c!==null){e="";for(var f=0;f<c.obj.cells.length;f++)e+=c.changedCells[f]?
"1":"0";b.AddMember("HasChanged",c.hasChanged);b.AddMember("ChangedCells",e)}}else if(c=="pagenum")b.AddMember("PageNum",this.pageNum);else if(c=="tree")b.AddMember("ExceptionKeys",this.GetTreeExceptionKeysForState());else if(c=="rows"){b.AddMember("ActivatedKey",this.GetActivatedKey());b.AddMember("ExceptionKeys",this.GetIsSelectedExceptionKeysForState())}else{b.AddMember("PageSize",this.pageSize);if(this.isUsingDefaultSort){b.AddMember("SortField",this.sortFieldForState);b.AddMember("SortDir",this.sortDirForState)}else{b.AddMember("SortField",
this.sortField);b.AddMember("SortDir",this.sortDir)}this.search&&b.AddMember("IsSearchExpanded",this.search.GetIsExpanded())}},GetValues:function(){var b=[],c,e;if(this.rowData&&this.rowData.allRows)for(c in this.rowData.allRows){e=this.rowData.allRows[c];e.type=="i"&&b.push(e.val)}return b},GetGroupSelectedKeys:function(){return this.GetSelectedGroupKeys()},GetGroupKeys:function(){var b=-1,c=[],e;if(this.rowData&&this.rowData.allRows)for(e in this.rowData.allRows){b=this.rowData.allRows[e];if(b.type==
"g"){b=e.indexOf("_");if(b>=0&&b<e.length)e=e.substr(b+1);c.push(e)}}return c},GetRowsByValue:function(b){var c=[],e,f;if(this.rowData&&this.rowData.allRows)for(e in this.rowData.allRows){f=this.rowData.allRows[e];f.type=="i"&&f.val==b&&c.push(f)}return c},GetActivatedKey:function(){return this.activatedKey},ForEachRow:function(b){var c,e;if(this.rowData&&this.rowData.allRows)for(c in this.rowData.allRows){e=this.rowData.allRows[c];b(e)}},ExpandAllTrees:function(){this.ForEachRow(function(b){b.type==
"i"&&b.Expand&&b.Expand()})},CollapseAllTrees:function(){this.ForEachRow(function(b){b.type=="i"&&b.Collapse&&b.Collapse()})},Activate:function(b){if(b===undefined||b===null)b="";b=b.toString();var c=this.GetRow(b);if(c){this.DeActivate();this.activatedKey=b;c.UpdateRowClass();for(b=c.Parent();b!==null;){b.Expand();b=b.Parent()}}},DeActivate:function(){var b=this.GetRow(this.activatedKey);if(b){this.activatedKey="";b.UpdateRowClass()}},RegisterSearch:function(b){this.search=b},Enable:function(){this.SetIsEnabled(true)},
Disable:function(){this.SetIsEnabled(false)},SetIsEnabled:function(b){this.isEnabled=b;if(!this.cb_sa1)this.cb_sa1=UI.GetById(this.GetMappedId()+"_cb_sa1");if(this.cb_sa1)this.cb_sa1.disabled=!b;if(!this.cb_sa2)this.cb_sa2=UI.GetById(this.GetMappedId()+"_cb_sa2");if(this.cb_sa2)this.cb_sa2.disabled=!b;this.ForEachRow(function(c){if(c.cbObj)c.cbObj.disabled=!b})},SetDisabledState:function(b){this.SetIsEnabled(!b)},GetSelectedKeysForType:function(b){var c=-1,e=[],f;if(this.rowData&&this.rowData.allRows)for(f in this.rowData.allRows){c=
this.rowData.allRows[f];if(c.type==b&&c.IsSelected()){c=f.indexOf("_");if(c>=0&&c<f.length)f=f.substr(c+1);e.push(f)}}return e},g_getRow:function(b){if(this.rowData&&this.rowData.allRows&&this.rowData.allRows[b])return this.rowData.allRows[b];return null},GetRow:function(b){var c=this.GetRowByType(b,"i");if(c===null)c=this.GetRowByType(b,"g");return c},GetRowByType:function(b,c){if(this.rowData)if(this.rowData.allRows){var e,f,g;for(e in this.rowData.allRows){f=this.rowData.allRows[e];if(f.type==
c){g=e.indexOf("_");if(g>=0&&g<e.length)e=e.substr(g+1);if(b==e)return f}}}return null},g_sr:function(b){b=this.g_getRow(b);this.SelectRow(b,b.cbObj.checked)},g_sd:function(b){b=this.g_getRow(b);b.Expand();var c,e=true;for(c in b.rows){var f=b.rows[c];if(f.doChildSelection){if(!f.AllDescendantsSelected(true)){this.SelectRow(f,true);e=false}}else if(!f.IsSelected()){this.SelectRow(f,true);e=false}}if(e)for(c in b.rows){f=b.rows[c];this.SelectRow(f,false)}},RemoveRow:function(b){var c=this.GetRow(b);
if(c!==null){var e=this;b=new YAHOO.util.Anim(c.obj,{opacity:{to:0}},0.5,YAHOO.util.Easing.easeOut);b.onComplete.subscribe(function(){WindowEventManager.BubbleRemoveEvent(c.obj);var f=e.IDomNode;if(f){f.deleteRow(c.obj.rowIndex);c.dObj&&f.deleteRow(c.dObj.rowIndex)}e.rowData&&e.rowData.RemoveRow(c)});b.animate()}},SelectAll:function(){this.g_sa(true)},UnSelectAll:function(){this.g_sa(false)},g_sa:function(b){var c=UI.GetByName(this.GetMappedId()+"_cb_sa");if(c.checked!==undefined)c.checked=b;else if(c.length==
2){c[0].checked=b;c[1].checked=b}var e;for(e in this.rowData.rows){c=this.rowData.rows[e];this.SelectRow(c,b)}},g_te:function(b){b=this.g_getRow(b);b.isExpanded?b.Collapse():b.Expand()},SelectRow:function(b,c){var e;if(b.type=="i"){if(b.HasSelection()){if(!this.SelectionAllowMultiple()&&c){var f=this;this.ForEachRow(function(h){h.IsSelected()&&f.SelectRow(h,false)})}b.cbObj.checked=c;b.isSelected=c;b.UpdateRowClass();if(!c)for(var g=b.m_parentGroup;g;){if(g.hasSelection&&g.m_linkDescendantSelection){g.isSelected=
false;g.cbObj.checked=false}g=g.m_parentGroup}if(!c)for(g=b.m_parent;g;){if(g.HasSelection()&&g.LinkDescendantSelection()){g.isSelected=false;g.cbObj.checked=false;g.UpdateRowClass()}g=g.m_parent}this.OnSelectRow.Trigger(b)}if(this.SelectionAllowMultiple()&&b.rows&&b.doChildSelection)for(e in b.rows)this.SelectRow(b.rows[e],c)}else if(b.type=="g"){if(b.hasSelection){b.isSelected=c;b.cbObj.checked=c}for(e in b.rows)this.SelectRow(b.rows[e],c)}},Init:function(){if(this.data){this.rowData=new D2L.GridRows(this);
for(var b=this.data.length,c,e=0;e<b;e++){c=this.data[e];if(e+1<b){this.rowData.AddElem(c,this.data[e+1]);!D2L.Util.JavaScript.IsArray(c)&&c.charAt(0)==this.rowData.item&&e++}else this.rowData.AddElem(c);this.m_rowIndex++}}},Sort:function(b,c,e){if(b!=this.sortField)this.pageNum=1;this.sortField=this.sortFieldForState=b;if(c)this.sortDir=this.sortDirForState=1;else this.sortDir=this.sortDirForState=2;e&&Nav.Go(new D2L.NavInfo)},SetPageNum:function(b,c){var e=this.pageNum,f=this,g=function(){f.pageNum=
b;f.m_slPgNm1&&f.m_slPgNm1.SelectOption(f.m_slPgNm1.GetOption(b),false);f.m_slPgNm2&&f.m_slPgNm2.SelectOption(f.m_slPgNm2.GetOption(b),false)};if(c){f.m_slPgNm1&&f.m_slPgNm1.SelectOption(f.m_slPgNm1.GetOption(e),false);f.m_slPgNm2&&f.m_slPgNm2.SelectOption(f.m_slPgNm2.GetOption(e),false);c=new D2L.NavInfo;c.OnNavigate.RegisterMethod(function(){g();f.OnPageNumberChange.Trigger(b)});Nav.Go(c)}else g()},SetPageSize:function(b,c){var e=this.pageSize,f=this,g=function(){f.pageSize=b;f.pageNum=1;f.m_slPgSz1&&
f.m_slPgSz1.SelectOption(f.m_slPgSz1.GetOption(b),false);f.m_slPgSz2&&f.m_slPgSz2.SelectOption(f.m_slPgSz2.GetOption(b),false)};if(c){f.m_slPgSz1&&f.m_slPgSz1.SelectOption(f.m_slPgSz1.GetOption(e),false);f.m_slPgSz2&&f.m_slPgSz2.SelectOption(f.m_slPgSz2.GetOption(e),false);c=new D2L.NavInfo;c.OnNavigate.RegisterMethod(function(){g();f.OnPageSizeChange.Trigger(b)});Nav.Go(c)}else g()},GetSearch:function(){return this.search},OnSearchChanged:function(){this.pageNum=1},OnNav:function(b){if(b&&b.IsAction()){for(b=
UI.GetById(this.GetMappedId()+"_values");b.hasChildNodes();){D2L.Util.Dom.Purge(b.childNodes[0]);b.removeChild(b.childNodes[0])}var c;if(this.rowData&&this.rowData.allRows)for(var e in this.rowData.allRows){c=this.rowData.allRows[e];if(c.type=="i"&&c.IsSelected()&&c.val!==""){var f=document.createElement("input");f.type="hidden";f.name=this.nameOrMappedId+"_vals";f.value=c.val;b.appendChild(f)}}}return true},SelectionAllowMultiple:function(){return this.m_selectionAllowMultiple},GetTreeType:function(){return this.m_treeType}});
D2L.Grid=D2L.Control.Grid;D2L.Control.Grid.Type={Data:1,List:2,NoLines:3};D2L.Grid.TreeType={StructureOnly:1,StructureHierarchy:2,StructureHierarchyLines:3};
D2L.GridRows=D2L.Class.extend({Construct:function(b){arguments.callee.$.Construct.call(this);this.item="i";this.details="d";this.header="h";this.group="g";this.summary="s";this.grid=b;this.rows=[];this.allRows=[];this.treeNodePeekIndex=-1;this.openTreeNodes=[];this.groupPeekIndex=-1;this.openGroups=[]},PeekGroup:function(){return this.groupPeekIndex<0?null:this.openGroups[this.groupPeekIndex]},PushGroup:function(b){this.groupPeekIndex++;this.openGroups[this.groupPeekIndex]=b},PopGroup:function(){this.groupPeekIndex--},
PeekItemTreeNode:function(){return this.treeNodePeekIndex<0?null:this.openTreeNodes[this.treeNodePeekIndex]},PushItemTreeNode:function(b){this.treeNodePeekIndex++;this.openTreeNodes[this.treeNodePeekIndex]=b},PopItemTreeNode:function(){this.treeNodePeekIndex--},AddRow:function(b){var c=this.PeekGroup();if(c)c.AddRow(b);else this.rows[b.key]=b;if(b.type==this.item)(c=this.PeekItemTreeNode())&&c.AddRow(b);this.allRows[b.key]=b},RemoveRow:function(b){var c,e,f=[];for(c in this.allRows){e=this.allRows[c];
if(e.key!=b.key)f[c]=e}this.allRows=f;f=[];for(c in this.rows){e=this.rows[c];if(e.type==this.group)e.RemoveRow(b);else if(e!=b)f[c]=e}this.rows=f},AddElem:function(b,c){var e;if(D2L.Util.JavaScript.IsArray(b)){e=b[0].charAt(0);var f=b[0];f=f.substring(1,f.length);c=1;if(e==this.group)this.OpenGroup(f);else if(e==this.item){this.OpenItemTreeNode(f,b[1]);c++}f=b.length;for(c=c;c<f;c++){this.grid.m_rowIndex++;if(c+1<f){this.AddElem(b[c],b[c+1]);!D2L.Util.JavaScript.IsArray(b[c])&&b[c].charAt(0)==this.item&&
c++}else this.AddElem(b[c])}if(e==this.group)this.CloseGroup();else e==this.item&&this.CloseItemTreeNode()}else{e=b.charAt(0);b=b.substring(1,b.length);if(e==this.item)this.AddItem(b,c);else if(e==this.header)this.AddHeader(b);else e==this.summary&&this.AddSummary(b)}},AddHeader:function(b){var c=new D2L.GridRow;c.grid=this.grid;c.type=this.header;c.key="h_"+b;c.obj=c.grid.GetDomNode().rows[c.grid.m_rowIndex];this.AddRow(c)},AddSummary:function(b){var c=new D2L.GridRow;c.type=this.summary;c.key="s_"+
b;c.obj=this.grid.IDomNode.rows[this.grid.m_rowIndex];this.AddRow(c)},OpenItemTreeNode:function(b,c){var e=this.AddItem(b,c);e.rows=[];e.isTreeNode=true;e.isExpanded=b.charAt(2)=="0"?false:true;e.isChild=b.charAt(4)=="0"?false:true;e.hasChildren=b.charAt(8)=="1";e.hasSiblings=b.charAt(9)=="1";e.isTopLevel=b.charAt(10)=="1";e.isFirstSibling=b.charAt(11)=="1";e.isLastSibling=b.charAt(1)=="1";e.ExpandHelper=GridExpandHelper;e.CollapseHelper=GridCollapseHelper;e.SetVisibleHelper=GridRowSetVisible;e.SetVisible=
function(f){e.SetVisibleHelper(f)};e.Expand=function(){this.isExpanded=true;this.SetTreeNodeImage();this.ExpandHelper();if(navigator.userAgent.indexOf("MSIE")==-1){this.SetVisible(false);this.SetVisible(true)}};e.Collapse=function(){this.isExpanded=false;this.SetTreeNodeImage();this.CollapseHelper()};e.SetTreeNodeImage=function(){if(this.treObj){var f=this.treObj.childNodes[0],g=this.isTopLevel&&!this.isFirstSibling?"t":"",h="",k=!this.isTopLevel?"l":"",j="",l="";if(this.isExpanded){h=this.hasChildren?
"b":"";j="Framework.Grid.actCollapse";l="Framework.Grid.altCollapseRow"}else{h=this.isTopLevel&&this.hasSiblings?"b":"";j="Framework.Grid.actExpand";l="Framework.Grid.altExpandRow"}D2L.Images.ImageTerm.Assign(j,f);j=new D2L.LP.Text.LangTerm(l);j.SetSubject(this.m_subject);j.AssignText(f,"title");j.AssignText(f,"alt");if(this.grid.GetTreeType()==D2L.Grid.TreeType.StructureHierarchyLines)this.treObj.parentNode.parentNode.className="d_g_l_"+g+"r"+h+k}};e.AddRow=function(f){f.m_parent=this;this.rows[f.key]=
f};for(b=0;b<e.obj.cells.length;b++)if(e.obj.cells[b].firstChild)if(e.obj.cells[b].firstChild.className=="d_gt"){e.treObj=e.obj.cells[b].firstChild.firstChild;break}else if(e.obj.cells[b].firstChild.className=="d_gts"){e.treObj=e.obj.cells[b].firstChild;break}this.PushItemTreeNode(e)},CloseItemTreeNode:function(){this.PopItemTreeNode()},AddItem:function(b,c){var e=new D2L.GridRow;e.type=this.item;e.grid=this.grid;e.m_subject=c[0];e.val=c[1];e.hasSelection=b.charAt(0)=="1"?true:false;e.hasDetails=
b.charAt(1)=="1"?true:false;e.isSelected=b.charAt(3)=="1"?true:false;e.doChildSelection=b.charAt(5)=="1"?true:false;e.isAlt=b.charAt(6)=="1"?true:false;e.m_linkDescendantSelection=b.charAt(13)=="1";var f=b.indexOf("_");c=b.lastIndexOf("_");f=b.substring(f+1,c);e.key=f;e.obj=e.grid.GetDomNode().rows[e.grid.m_rowIndex];this.AttachObject(e.obj,"rowObj",e);if(e.hasSelection)for(f=0;f<e.obj.cells.length;f++)if(e.obj.cells[f].firstChild&&e.obj.cells[f].firstChild.name&&e.obj.cells[f].firstChild.name==this.grid.nameOrMappedId+
"_cb"){e.cbObj=e.obj.cells[f].firstChild;break}if(e.hasDetails){e.dObj=e.obj.nextSibling;e.grid.m_rowIndex++}f=b.charAt(7);if(f=="2")e.HandleOnChange(new D2L.ChangeEvent(e.obj));else if(f=="1"){this.AttachObject(e.obj,"ID2LOnChange",new D2L.EventHandler);e.obj.ID2LOnChange.Register(e,"HandleOnChange")}for(f=c+1;f<b.length;f+=2)if(b.charAt(f)=="1"){var g=(f-(c+1))/2;if(b.charAt(f+1)=="1")e.HandleCellOnChange(new D2L.ChangeEvent(e.obj.cells[g]));else{this.AttachObject(e.obj.cells[g],"ID2LOnChange",
new D2L.EventHandler);e.obj.cells[g].ID2LOnChange.Register(e,"HandleCellOnChange")}}e.IsSelected()&&e.UpdateRowClass();this.AddRow(e);return e},OpenGroup:function(b){var c=new D2L.GridGroup;if(b.charAt(0)=="1")c.hasSelection=true;if(b.charAt(1)=="0")c.isExpanded=false;if(b.charAt(2)=="1")c.m_linkDescendantSelection=true;b=b.substring(3,b.length);c.type=this.group;c.key=b;c.obj=this.grid.IDomNode.rows[this.grid.m_rowIndex];c.cbObj=UI.GetById(this.grid.GetMappedId()+"_cb"+b);c.exObj=UI.GetById(this.grid.GetMappedId()+
"_ex"+b);this.AddRow(c);this.PushGroup(c)},CloseGroup:function(){this.PopGroup()}});
D2L.GridRow=D2L.Class.extend({Construct:function(){arguments.callee.$.Construct.call(this);this.m_isDeleted=false;this.grid=null;this.hasChanged=false;this.changedCells=[];this.m_hiddenDeleted=this.m_hiddenChanged=null;this.val="";this.m_parent=this.m_parentGroup=null;this.isSelected=false;this.m_initialClass=null;this.m_hasSpecifiedKey=this.m_linkDescendantSelection=false;this.m_subject="";FormManager.OnChangeReset.Register(this,"HandleOnChangeReset")},GetSubject:function(){return this.m_subject},
LinkDescendantSelection:function(){return this.m_linkDescendantSelection},HasSelection:function(){return this.hasSelection},UpdateRowClass:function(){if(this.m_initialClass===null)this.m_initialClass=this.obj.className;var b="";if(this.grid.activatedKey.length>0&&this.GetKey().length>0&&this.grid.activatedKey==this.GetKey())b=" d_ga";else if(this.hasChanged)b=" d_gc";else if(this.IsSelected())b=" d_gs";var c="";if(this.IsDeleted())c=" d_gdel";b=this.m_initialClass+b+c;this.obj.className=b;if(this.hasDetails)this.dObj.className=
b},SetTextFormat:function(b){b=b.toLowerCase();var c=this.obj.className;if(b=="normal"){if(c.indexOf("d_dbold")>=0){this.obj.className=c.replace("d_dbold","");if(this.m_initialClass)this.m_initialClass=this.m_initialClass.replace("d_dbold","")}}else if(b=="bold")if(c.indexOf("d_dbold")<0){this.obj.className+=" d_dbold";if(this.m_initialClass)this.m_initialClass+=" d_dbold"}},HandleOnChange:function(b){if(!b.hasChangeBeenShown){if(!this.hasChanged){this.hasChanged=true;this.UpdateRowClass()}b.hasChangeBeenShown=
true}if(this.m_hiddenChanged===null){this.m_hiddenChanged=document.createElement("input");this.m_hiddenChanged.type="hidden";this.m_hiddenChanged.value=this.GetKey();this.obj.firstChild.appendChild(this.m_hiddenChanged)}this.m_hiddenChanged.name=this.grid.nameOrMappedId+"_ckeys"},HandleCellOnChange:function(b){if(!b.hasChangeBeenShown){b=b.source;for(var c=null;b!=this.obj;){c=b;b=b.parentNode}this.hasChanged=true;this.changedCells[c.cellIndex]=true;c.className+=" d_gch"}},HandleOnChangeReset:function(){this.hasChanged=
false;this.UpdateRowClass()},HasSpecifiedKey:function(){return this.m_hasSpecifiedKey},GetKey:function(){var b=this.key.indexOf("_");if(b>=0&&b<this.key.length)return this.key.substr(b+1);return""},GetValue:function(){return this.val},SetVisible:GridRowSetVisible,Delete:function(){if(!this.IsDeleted()){if(this.m_hiddenDeleted===null){this.m_hiddenDeleted=document.createElement("input");this.m_hiddenDeleted.type="hidden";this.m_hiddenDeleted.value=this.GetKey();this.obj.firstChild.appendChild(this.m_hiddenDeleted)}this.m_hiddenDeleted.name=
this.grid.nameOrMappedId+"_dkeys";this.m_isDeleted=true;this.UpdateRowClass();WindowEventManager.BubbleChangeEvent(this.obj);this.grid.OnDeleteRow.Trigger(this)}},IsDeleted:function(){return this.m_isDeleted},IsSelected:function(){return this.isSelected},HasSelectedDescendant:function(b){if(b&&this.IsSelected())return true;for(var c in this.rows)if(this.rows[c].HasSelectedDescendant(true))return true;return false},AllDescendantsSelected:function(b){if(b&&!this.IsSelected())return false;for(var c in this.rows)if(!this.rows[c].AllDescendantsSelected(true))return false;
return true},Restore:function(){if(this.IsDeleted()){this.m_hiddenDeleted.name="";this.m_isDeleted=false;this.UpdateRowClass();this.grid.OnRestoreRow.Trigger(this)}},SetIsDeleted:function(b){if(!this.IsDeleted()&&b)this.Delete();else this.IsDeleted()&&!b&&this.Restore()},ToggleIsDeleted:function(){this.SetIsDeleted(!this.IsDeleted())},SetDoChildSelection:function(b){this.doChildSelection=b},DoChildSelection:function(){return this.doChildSelection},Parent:function(){return this.m_parent},SetBackgroundColour:function(b){this.obj.style.backgroundColor=
b},GetCellByIndex:function(b){for(var c=this.obj.getElementsByTagName("td"),e=0;e<c.length;e++){var f=c[e];if(f.parentNode==this.obj)if(b==0)return f;else b--}return null},SetCellBackgroundColour:function(b,c){this.GetCellByIndex(b).style.backgroundColor=c},SetCellOnMouseOver:function(b,c){this.GetCellByIndex(b).onmouseover=c},SetCellOnMouseOut:function(b,c){this.GetCellByIndex(b).onmouseout=c},SetCellOnMouseClick:function(b,c){this.GetCellByIndex(b).onclick=c},SetCellProperty:function(b,c,e){this.GetCellByIndex(b)[c]=
e}});
D2L.GridGroup=D2L.Class.extend({Construct:function(){arguments.callee.$.Construct.call(this);this.rows=[];this.doChildSelection=true;this.itemRows=[];this.m_linkDescendantSelection=false;this.m_parentGroup=null;this.isSelected=false},SetVisible:GridRowSetVisible,ExpandHelper:GridExpandHelper,CollapseHelper:GridCollapseHelper,Expand:function(){if(this.exObj)this.exObj.innerHTML='<img style="border:none;" src="/d2l/tools/img/up.gif" width="6" height="8" alt="Collapse Group" title="Collapse Group" />';this.isExpanded=
true;this.ExpandHelper()},Collapse:function(){if(this.exObj)this.exObj.innerHTML='<img style="border:none;" src="/d2l/tools/img/down.gif" width="6" height="8" alt="Expand Group" title="Expand Group" />';this.isExpanded=false;this.CollapseHelper()},AddRow:function(b){b.m_parentGroup=this;this.rows[b.key]=b},IsSelected:function(){return this.isSelected},RemoveRow:function(b){var c=[];for(currKey in this.rows){currRow=this.rows[currKey];if(currRow.type==this.group)currRow.RemoveRow(b);else if(currRow!=
b)c[currKey]=currRow}this.rows=c}});function GridExpandHelper(){for(var b in this.rows){var c=this.rows[b];c.SetVisible(true);if(c.type=="g"||c.type=="i"&&c.rows)c.isExpanded&&c.ExpandHelper()}WindowEventManager.Transform.Trigger()}function GridCollapseHelper(){for(var b in this.rows){var c=this.rows[b];c.SetVisible(false);if(c.type=="g"||c.type=="i"&&c.rows)c.CollapseHelper()}WindowEventManager.Transform.Trigger()}
function GridRowSetVisible(b){this.isVisible=b;this.obj.style.display=b?navigator.userAgent.indexOf("MSIE")!=-1?"inline":"table-row":"none"}window.D2L!==undefined&&D2L.LP.Web.Packaging!==undefined&&D2L.LP.Web.Packaging.Register("D2L.LP.Web.Controls.Grid");